### ISSUE TITLE
mzML files in msdata package missing

### ISSUE THREAD

**Issue by jotsetung** [lgatto/MSnbase#121]
I just realized that in version 0.12.0 of the msdata package the mzML files I'm using for the testing are missing (i.e. the inst/microtofq folder is missing). Was there a reason for removing them?

**Comment by lgatto** [comment]
Hmm, that was certainly not intentional. Will investigate.

**Comment by lgatto** [comment]
How did you install the package? If you pulled from subversion, that would be the reason. 
`data`, `inst/lockmass`, `inst/microtofq` and `inst/threonine` live in an external repository (that's actually the default for data packages). Or did you use `biocLite`?

**Comment by jotsetung** [comment]
My fault; I installed from svn; using `biocLite` I get version 0.11.0 (even if using BioC 3.4 devel version). I guess the version 0.12.0 was not built yet. For now I just manually added the files to the package I checked out from svn.

**Comment by lgatto** [comment]
FYI

How to Create an Infrastructure-Only Workingcopy
================================================

You can obtain a checkout of all experiment data package
infrastructure files as follows::

    svn checkout \
      https://hedgehog.fhcrc.org/bioc-data/trunk/experiment/pkgs

To obtain the files for a particular package, say ``ALL``::

    svn checkout \
      https://hedgehog.fhcrc.org/bioc-data/trunk/experiment/pkgs/ALL

If you want to preview what is available, you might try the
following::

    # get the top-level scripts, but don't recurse into subdirs        
    svn checkout -N \
      https://hedgehog.fhcrc.org/bioc-data/trunk/experiment/pkgs

    # see what is there
    svn ls https://hedgehog.fhcrc.org/bioc-data/trunk/experiment/pkgs

    # get a particular package's infrastructure files
    cd pkgs
    svn up ALL
    # see next section for getting complete working copy w/ data


How to Create a Complete Workingcopy
====================================

First create a workingcopy of the infrastructure files as described
above.

Next use the helper script ``add_data.py`` (you will need Python).  It
is located here:

    https://hedgehog.fhcrc.org/bioc-data/trunk/experiment/pkgs/add_data.py

Here's a complete example for ``ALL``::

    svn checkout \
      https://hedgehog.fhcrc.org/bioc-data/trunk/experiment/pkgs/ALL

    python add_data.py ALL

This will add the big data directories (usually data/, but sometimes
also dirs under inst/) to your working copy.  Usually, the svn:ignore
property has been set so that you won't accidentally add these dirs
when working with the package, but please take care anyway.

**Comment by lgatto** [comment]
If we anticipate more changes to `msdata`, we could create a github repo to facilitate development and collaboration.
