### ISSUE TITLE
issue with pickPeaks,OnDiskMSnExp

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#133]
The method simply queues the peak picking:

```r
## pickPeaks
setMethod("pickPeaks", "OnDiskMSnExp",
          function(object, halfWindowSize = 3L,
                   method = c("MAD", "SuperSmoother"),
                    SNR = 0L, ...) {
              method <- match.arg(method)
              ps <- ProcessingStep("pickPeaks",
                                   list(method = method,
                                        halfWindowSize = halfWindowSize,
                                        SNR = SNR, ...))
              object@spectraProcessingQueue <- c(object@spectraProcessingQueue,
                                                 list(ps))
              object@processingData@processing <- c(object@processingData@processing,
                                                    paste0("Peak picking (",
                                                           method, "): ", date()))
              fData(object)$centroided <- TRUE
              if (validObject(object))
                  return(object)
          })
```

There is however a problem when the actual peak picking is executed, because
* the list of spectra is constructed based on the `fData` information, which contains `centroided` is `TRUE`, so that `sp@centroided` is `TRUE`
* but, `pickPeaks_Spectrum` checks checks `sp@centroided` and doesn't do anything if already `TRUE`. 

I can think of an `if` check upon spectrum construction or before `execute` that changes `@centroided` to `FALSE` if `pickPeaks` is in the queue. But that's rather ugly. 

@jotsetung - do you have any better suggestion?

**Comment by jotsetung** [comment]
That's a tricky one. And what about:
+ Add an additional argument `force = TRUE` to `pickPeaks_Spectrum` that ignores the `sp@centroided`?

Changing `centroided` in the spectra construction might be a problem if there are more steps in the queue, since it would be quite tricky to just change `centroided` for that one step, and not for all. Thus I would prefer to use an additional argument that is passed to the function in the processing step; or wrap the `pickPeaks_Spectrum` inside another function, something like:

```{r}
pickPeaks_Spectrum_uncentroided <- function(x, halfWindowSize, method, SNR, ...) {
    x@centroided <- FALSE
    return(pickPeaks_Spectrum(x, halfWindowSize, method, SNR, ...))
}
```

Haven't tried that, but eventually that might also be a solution.

**Comment by lgatto** [comment]
Good suggestions. I am about to add an `ignoreCentroided` argument to `pickPeaks_Spectrum`.
