### ISSUE TITLE
Allow different colours for different fragment types in `.plotSpectrumVsSpectrum`

### ISSUE THREAD

**Issue by sgibb** [lgatto/MSnbase#147]
cf. title; extracted from #129 

> To make the figure nicer, i want to do the following small changes.
> draw all peaks in grey, color the peaks that can be annotated as b, y ions (b ions blue, y ions red if possible)

CC: @yafeng

**Comment by sgibb** [comment]
I am wondering how to solve this problem. In fact it would result in a big list of arguments, especially if we want to combine it with #148, #149 , e.g.

- spectrum.a.peaks.common.{col,cex,lwd,pch}
- spectrum.a.peaks.{col,cex,lwd,pch}
- spectrum.a.precursor.{col,cex,lwd,pch}
- spectrum.a.fragments.{a,b,c,x,y,z,aIx,bIy,cIz,neutralloss}.{col,cex,lwd,pch}
- spectrum.a.fragments.text.{col,cex,lwd,pch}

and the same for `spectrum.b`.

Any suggestions?

**Comment by yafeng** [comment]
Thanks for taking this into consideration!  
As a user, I would say #148 issues have been fixed nicely.  

Regarding the feature to colour different types of ions in different colours, I understand your concern. it will result too many arguments.

In the end it is the four categories we want to colour differently. 
spectrum.all.peaks (i want to set in grey instead)
spectrum.peaks.common {col,cex,lwd,pch}, (set in darker color )
spectrum.fragments (bcol="blue", ycol="red")
spectrum.precursor {col,cex,lwd,pch}  - nice to have

I would not bother to  set a different list of arguments for spectrum b,  because in the mirror image we often have same graphic setting for both spectrum a and b.
