### ISSUE TITLE
addIdentificationData problem

### ISSUE THREAD

**Issue by mchiapello** [lgatto/MSnbase#158]
Using the attached data the function "addIdentificationData" is not able to find matches between raw and identification files.

The files can be download following this link:
[https://mega.nz/#F!ntohVTLC!uFrUy9hgwJ_A0C1t_f_0FQ](url)

Thank you,
Marco

**Comment by lgatto** [comment]
I think this problem is because the mzid files are version 1.0. The current version is 1.1 and 1.2 is scheduled for release. I can't commit time if assuring backwards compatibility for now. I would suggest to read the mzid file using `mzID` or `mzR` and merge the feature data and the identification `data.frame` manually. Let me know if you need any help with that.
