### ISSUE TITLE
removeReporters,OnDiskMSnExp

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#161]
Added a `removeReporters,OnDiskMSnExp` that coerces to an `MSnSet` in bab8b0d787d9644e89f60f979465eaa2ff3f091d. Needs to use lazy processing.

**Comment by lgatto** [comment]
cc @jotsetung

**Comment by jotsetung** [comment]
I'll have a look at it.

**Comment by jotsetung** [comment]
Simply adding `removeReporters` to the lazy processing queue does not work for `OnDiskMSnExp` with MS1 and MSn spectra, because as soon as a `Spectrum1` is processed an error is thrown by the `removeReporters,Spectrum` class. I applied the following modification for it to work (in commit https://github.com/lgatto/MSnbase/commit/8d7ec823247cdd6eb4ea0d3c8200238b7631e969):
+ `removeReporters,Spectrum` does not throw an error is `msLevel == 1`, but a warning.
+ The `removeReporters,Spectrum` has an internal parameter `suppressWarning` that allows to suppress the above warning. This is because we don't want to get a warning message for each `Spectrum1` in an `OnDiskMSnExp` object. I went for an internal parameter, as this parameter should not be visible to the user.
+ The `removeReporters,MSnExp` throws an error if all spectra are MS1.
+ The `removeReporters,OnDiskMSnExp` throws an error if all spectra are MS1.

Are you OK with that?

**Comment by lgatto** [comment]
Looks good, thanks.

**Comment by lgatto** [comment]
@jotsetung - can we close this?

**Comment by jotsetung** [comment]
happy to do that

**Comment by lgatto** [comment]
Closing issues feels so rewarding :-)

**Comment by jotsetung** [comment]
Yes, true; but sorry, I didn't wanted to sneak that from you, if you want I can re-open and you can close it ;-)
