### ISSUE TITLE
as,MSnExp,OnDiskMSnExp

### ISSUE THREAD

**Issue by jotsetung** [lgatto/MSnbase#162]
Might eventually be nice to have a coercion method from `MSnExp` to `OnDiskMSnExp`. This method should ensure:
- check that the files are available
- extract all necessary data from the `spectra` and put it into the `featureData`.
- validate the object.

**Comment by lgatto** [comment]
But the problem is that any operations would need to be recorded in the `spectraProcessingQueue`, but what is recorded in `processingData@processing` is *just* a string. I think, for this to be possible, we would need to have a `spectraProcessingQueue` in `MSnExp` objects too. 

Or, may be more easily/straightfoward, would be to implement writing `mzML` files from `MSnExp` objects.

**Comment by jotsetung** [comment]
Yes, you're right. didn't think of the processing steps. let's postpone this one.
