### ISSUE TITLE
Problem with updateObject

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#166]
As described in this [post to Bioc-devel](https://stat.ethz.ch/pipermail/bioc-devel/2016-October/009868.html), we have a problem with `updateObject` on `Spectrum` instances because the class version is not set in the prototype (see issue #163 for more details).

This lead to `test_updateObjects.R` to fail. That failing test is now momentarily disabled until we identify a way to fix this.

**Comment by meowcat** [comment]
Hi,

is this forever unfixed? I am preparing a pull request (cf #454, annotated spectrum, the current opinion of the taskforce is to add the fields to Spectrum instead of making a seprate class) that would update Spectrum. 

I can circumvent the vignette and unit-test issues by updating data/itraqdata.RData and inst/extdata/msx.rda manually (for now these are the two I have identified), otherwise they will not load correctly. My question relates more to the general ideas for the updating function.

(Note: I personally will drop updating in http://github.com/MassBank/RMassBank for breaking changes.)

**Comment by lgatto** [comment]
I had forgotten about this. I can't answer now, but this will come up soon with the new developments.
