### ISSUE TITLE
Using markdown for NEWS.md

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#179]
Along the lines of #176, I have moved `NEWS` to `NEWS.md` with some reformatting.

```
commit 2fb533180c6b9e0b611a8088dabe94e074f2f424
Author: Laurent <lg390@cam.ac.uk>
Date:   Fri Dec 23 15:36:14 2016 +0000

    Move NEWS to NEWS.md
    
    The NEWS file is not in markdown format. Major version are first
    level sections and should only comprise x.y version numbers. z-level
    changes are documented as second level section starting with
    'Changes in version x.y.z'.
    
    This change is motivated by the use of 'pckdown' to generate package
    webpages, which does not support anything other than NEWS.md.
```

I would consider to have more structured `NEWS.md` file, with *Bug fixes*, *New features*, *User visible changes*, ... but I also like to be able to track changes at the patch (`z`) level.

@sgibb @jotsetung - any comments or suggestions.

**Comment by lgatto** [comment]
Have a look http://lgatto.github.io/MSnbase/ or http://lgatto.github.io/hpar/ for some `pkgdown` examples.

**Comment by sgibb** [comment]
I like the idea of having a more structured `NEWS.md` file (and also the idea of `pkgdown` generated documentation). On CRAN `NEWS.md` and `README.md` are rendered by `pandoc` into html. Does bioconductor do the same?

Unfortunately `news(package="MSnbase")` is not working with `NEWS.md`. E.g. see `news(package="MALDIquant")` for a working example (looks very markdown like but is not rendered by github because of a missing `.md`).

**Comment by lgatto** [comment]
> On CRAN NEWS.md and README.md are rendered by pandoc into html. Does bioconductor do the same?

For a plain `NEWS`, Bioconductor links to it as text. Not sure what happens if it's md.

> Unfortunately news(package="MSnbase") is not working with NEWS.md. E.g. see news(package="MALDIquant") for a working example (looks very markdown like but is not rendered by github because of a missing .md).

Shit, I thought it was supported. Now I'm wondering what is the best thing, `md` or `Rd`? I suspect that `news(...)` is not used by many and opting for md is possibly better for exposure. Also, I suspect that md will be supported at some point (see the `format` argument in `?news`). Still, this is annoying... 
What do you think?

**Comment by sgibb** [comment]
What about providing both `NEWS.md` and `NEWS` in the meantime? A simple `sed 's/^# .*$\|^## //g' NEWS.md > NEWS` would be sufficient. Please note that `news(package="MSnbase")` doesn't work if there are empty entries like the current 2.1.7; should not be a problem because the released package doesn't contain such entries.

`maker` could look for a `NEWS.md` and convert it to `NEWS` before building the package. What do you think? (bioc and CRAN would possibly use the `NEWS` file instead of a pandoc generated `NEWS.html` so it would not look fancy on their webpages ...)

**Comment by lgatto** [comment]
Good idea for a `NEWS.md > NEWS` in `maker`. That way we can get both options. 

I have also added have a `README.Rmd > README.md` recipe (see [here](https://github.com/lgatto/MSnbase/commit/d342c70769d411e2c0ca8df54536c2054c95f25e))

**Comment by sgibb** [comment]
There is a new `NEWS` target in `maker`. As mentioned above it is a very simple `sed 's/^# .*$\|^## //g' NEWS.md > NEWS` call. Do we need something more sophisticated?

**Comment by lgatto** [comment]
I think that's enough (for not at least). I am going to add `NEWS.md` to `.Rbuildignore` and possibly `NEWS` to `.gitignore` so that we only have one of each in the package and on GitHub.

**Comment by lgatto** [comment]
I am closing this issue but would appreciate comments on how to better structure the `NEWS.md` file. 

I feel a bit conflicted about the Bioconductor versioning and the resulting extensive number of version in the `NEWS.md` file and trying to document *Bug fixes*, *New features*, *User visible changes*, ... under different sub-sections. Comments/suggestions welcome.
