### ISSUE TITLE
Transition away from readMSData2

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#233]
Users should start using `readMSData2` and on-disk objects, as these are going to be developed further. I would like to gather feedback here on how to do this best.

1. Keep `readMSData` and `readMSData2` and use the latter in all documentation and add a message to the first one advising to the the new one.

2. Replace `readMSData` with `readMSData2` and rename the former `readInMemMSData` (or something like that).

@jotsetung @sgibb - any ideas or suggestions?

**Comment by jotsetung** [comment]
I would go for option 1). Replacing might be confusing for users that are already using `readMSData2` (don't know how many there are).

**Comment by lgatto** [comment]
But, in the long run, wouldn't it be better to have a cleaner interface. Keeping `readMSData` and `readMSData2` obscures things. 

Another solution would be to have `readInMemMSData` and `readOnDiskMSData`, to make things explicit, and have `readMSData` to point to the latter. 

Any solution that involves such changes would be done over 1 or 2 releases, with messages informing users of what is going to happen. Also, during that transition phase, we would need to make sure that things (by that I mean the vignette, essentially) work equally with either on-disk or in-memory.

**Comment by jotsetung** [comment]
OK, let's go for the `readOnDiskMSnData` then. Makes sense.

**Comment by sgibb** [comment]
I think a cleaner interface would be good. IMHO `readMSData,MSnExp` (the `readMSData` that returns an `MSnExp` object) is not needed anymore (and `readInMemMSData` neither). 
In general I don't like `readInMemMSData` and `readOnDiskMSData` because the use has to think about implementation details without knowing the risks and benefits. I would suggest to provide just one function to import ms data (e.g. `readMSData,OnDiskMSnExp`).

What about adding an argument `useOnDiskMSnExp` to `readMSData`. If `FALSE` (current default) the current `readMSData,MSnExp` would be used if `TRUE` the `readMSData2` is used. Additionally we show a message in the next release cycle that we are planing to change the default value for `useOnDiskMSnExp` to `TRUE` in the over-next release:

- Bioc 3.6: message + argument `useOnDiskMSnExp=FALSE` in `readMSData`, `readMSData2` is an alias for `readMSData(..., useOnDiskMSnExp=TRUE)`
- Bioc 3.7: argument `useOnDiskMSnExp=TRUE` + message that `useOnDiskMSnExp=FALSE` will be deprecated in the next release, `readMSData2` deprecated
- Bioc 3.8: deprecate `useOnDiskMSnExp=FALSE` + message that `useOnDiskMSnExp` (if given by the user) will be removed in the next release, `readMSData2` defunct
- Bioc 3.9: remove `useOnDiskMSnExp` argument and `readMSData,MSnExp`, remove `readMSData2`

That would be a long way with a lot of changes but will result in a clean interface with a good name `readMSData`.

Nevertheless I want to vote for keeping the original `MSnExp` class in place. There are situations where you have file formats that are not supported by `mzR` (e.g. in `synapter`). Without file format support you can't use `OnDiskMSnExp` (but you don't need `readMSData,MSnExp` in this cases but have to build the `MSnExp` by yourself).

**Comment by jotsetung** [comment]
Good point @sgibb . One additional note: if I remember correctly there is a function to convert an `OnDiskMSnExp` to a `MSnExp`. `readMSData` could then just return an `OnDiskMSnExp`, if the user still wants to use `MSnExp` he/she can convert it easily.

**Comment by lgatto** [comment]
I am inclined to have 
```r
readMSData(..., mode = c("OnDisk", "InMem")
```
so that we could add other modes later on. 

The `readMSData` documentation will be a bit long, as the two modes have slightly different parameters, or support different values for the same paramters, but nothing too complicated, as far as I can remember.

Thank you for your inputs!

**Comment by lgatto** [comment]
This has now been implemented in a series of recent commits (mainly e72c3f28dc3b76c830dbd8252f11baa5109a9b7d). The anticipated plan is as follows:

- Bioc 3.6 (now): In devel, `readMSData` has modes `inMemory` (default) and `onDisk`. `readMSData2`now deprecated (commit 6e6062a722f88044b8dd70335b5744efafb5bcbd), and users are asked to switch to `readMSData(..., mode = "onDisk")`
- Bioc 3.7: `readMSData2` will be deprecated in release. In devel, defunct `readMSData2` and switch to `onDisk` as new default. 
- Bioc 3.8: In release, `readMSData2` will be defunct and `onDisk` will be the new default.

I don't think we need to remove `inMemory` altogether. At least no need to plan for it already now. I think we can discuss this when we switch to `onDisk` as new default (Bioc 3.7). 

In Bioc 3.7, we we start using `onDisk` as new default, we might add a message in `readMSData` to make it explicit. 

@sgibb @jotsetung - any comments on this?

**Comment by jotsetung** [comment]
Perfect! looks like a plain transition.
Q: but we are not going to remove the `MSnExp` class, are we? If yes, that would be a major rebuild, since `OnDiskMSnExp` directly extends `MSnExp`...

**Comment by lgatto** [comment]
> Q: but we are not going to remove the MSnExp class, are we?

Absolutely no plans to do that. At this stage, I would even want to keep `readMSData(..., mode = "onDisk")` and hence `MSnExp` objects.

**Comment by sgibb** [comment]
Great. I am fine with this transition plan.

As I mentioned above we have to keep `MSnExp` because of `OnDiskMSnExp` but also because some software with awkward file formats rely on `MSnExp` (e.g. `synapter`).

**Comment by lgatto** [comment]
Sorry for the confusion - `MSnExp` **will not** be deprecated, of course.

**Comment by lgatto** [comment]
`readMSData2` is now defunct.
