### ISSUE TITLE
Rationalise code in addIdentificationData methods

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#235]
The code in the `addIdentificationData,MSnExp` and `addIdentificationData,MSnSet` methods was essentially duplicated (except when `id` is a `data.frame` - see below). That code has been moved to a set of common functions in [`functions-addIdentificationData.R`](https://github.com/lgatto/MSnbase/blob/master/R/functions-addIdentificationData.R) that do the data preparation (i.e. converting to a `data.frame` and set the arguments (added in d1319daf7cd3968775cad6d0373c8a50632b9d3f). 

The call stack is now, for either object of class `MSnExp` of `MSnSet`:
```
addIdentificationData,object,character calls .addCharacterIdentificationData calls addIdentifcationData,object,data.frame
addIdentificationData,object,mzRident  calls .addMzRidentIdentificationData  calls addIdentifcationData,object,data.frame
addIdentificationData,object,mzID      calls .addMzIDidentIdentificationData calls addIdentifcationData,object,data.frame
```

The respective `addIdentificationData,object,data.frame` code is still different, but I am wondering if this is correct, and whether they shouldn't be merged too. 

@sgibb, could you review this code and comment on the `addIdentificationData,object,data.frame` question.

**Comment by sgibb** [comment]
@lgatto great work! The code is much cleaner and easier to read now! 

`addIdentificationData,[MSnExp|MSnSet],data.frame` just differ in two lines:

```r
# MSnExp
fd$spectrum.file <- basename(fileNames(object)[fromFile(object)])
fd$acquisition.number <- acquisitionNum(object)
# ...
keep <- cn[!(cn %in% c("spectrum.file", "acquisition.number"))]

# MSnSet
fd$spectrum.file <- basename(fileNames(object)[fd$file])
## FIXME why no acquisition number here?
# ...
keep <- cn[!(cn %in% c("spectrum.file"))] 
```

As you know the whole matching is done on `spectrum.file` and `acquisition.number`. That's why we temporary add them to the `featureData` `data.frame`. `spectrum.file` is simple and identical for `MSnExp` and `MSnSet`. The `acquisition.number` is stored different in `MSnExp` and `MSnSet`. While in an `MSnExp` object each `Spectrum*` object stores its own  `acquisition.number` (and `acquisitionNum` is available) there is no  `acquisition.number` column in the `featureData` slot.
For an `MSnSet` object the  `acquisition.number` is stored as a column in the `featureData` slot (introduced by calling `header` in `quantify`; `acquisitionNum` is not implemented). That's why we need to add an `acquisition.number` column to the `featureData` `data.frame` in `addIdentificationData,MSnExp,data.frame` but not in `addIdentificationData,MSnSet,data.frame`. Finally we remove the temporary added columns from the `featureData` `data.frame`. For `MSnSet` we don't want to remove the `acquisition.number` column otherwise the information would be lost completely.

Things we could consider to use exactly the same implementation for both:

1. Don't remove the `acquisition.number` column for `MSnExp` (would be overwritten by `acquisitionNum` anyway).
2. Implement `acquisitionNum` for `MSnSet` (could just return `featureData(msnset)["acquisition.num"]`).

Or a simple `if(is(object, "MSnExp")) fd$acquisition.number <- acquisitionNum(object)` at the beginning and at the end `if(is(object, "MSnExp")) fd$acquisition.number <- NULL`.

**Comment by lgatto** [comment]
Thanks for the details, Seb. 

I would prefer to harmonise the two as much as possible so that we can use exactly the same code in `addIdentificationData,[MSnExp|MSnSet],data.frame`. For that, yes, let have an `acquisitionNum,MSnSet` accessor, that fetches `fcol = "acquisition.num" from the feature data, and let's keep that feature variable in the `MSnExp`. 

Let me know if you can do it, otherwise, I will have a go at some point.

**Comment by sgibb** [comment]
I will do it.

**Comment by sgibb** [comment]
@lgatto there are a lot of failing unit tests regarding `addIdentificationData`. One reason is the fact that you introduce `reduce`. Before (as you can see at https://github.com/lgatto/MSnbase/blob/master/R/utils.R#L819-L829) we concatenate just a few columns (acc, desc, npept) and took the best matching peptide (`rank == 1`) for all the other columns. 
If I remember correctly we did this because functions like `calculateFragments` can't handle `PEPTIDESEQUENCE1;PEPTIDESEQUENCE2` as input. As compromise we said we keep just the best match but the accession numbers of all possible matches and if anybody wants to know the sequences of the peptide with `rank >= 1` he could look up the missing information.
(by commenting the `reduce` calls most of the unit tests could be corrected because `utils.mergeSpectraAndIdentificationData` does the reduction (but slightly different as mentioned above))

Currently I just added `acquisitionNum,MSnSet` and `.addDataFrameIdentificationData` into a new branch https://github.com/lgatto/MSnbase/tree/addIdentificationData

**Comment by sgibb** [comment]
BTW the `closes #235` in the commit message was a bit overoptimistic. Sorry.

**Comment by lgatto** [comment]
> there are a lot of failing unit tests regarding `addIdentificationData`.

Yes, sorry about that. It's `reduce` as well as other changes (for example, using `merge` rather that `left_join` had unexpected consequences with names for `mzID` objects).

The reason we need `reduce` is that there are multiple peptides per scan, even if we keep only rank 1: for example if a peptide matches to multiple proteins, or when there are multiple modifications per peptide (none of these cases happened with the simple test data). Basically, we need now to apply more filters (rank, unique prot, decoy, ...) implicitly, which I still want to think a bit more about. 

The pipeline I am currently thinking of is:
1. Explore your identification data as a data.frame using default tools and tidyverse.
2. Either choose default filtering (rank 1, ....) or filter the data.frame yourself and add it with `addIdentificationData,data.frame`. 

I think this is preferable to another class for identification data, ... I also want it to fit well with `MSnID`.

**Comment by lgatto** [comment]
Thanks for the contribution!
Could to merge your `addIdentificationData` into master, so that I have everything at hand when I carry on this work - I should have created a new branch!
