### ISSUE TITLE
ggplot2 based plotting functionality for plot,Chromatogram

### ISSUE THREAD

**Issue by jorainer** [lgatto/MSnbase#237]
@stanstrup did some nice implementations to have ggplot2-based plotting functionality for `Chromatogram` and `Chromatograms` objects (see https://github.com/sneumann/xcms/issues/172).

We were wondering if we shouldn't add this functionality to `MSnbase`.

I would still like to keep the base R graphics plotting methods `plot,Chromatogram` and `plot,Chromatograms` but we could have in addition ggplot based methods too (`ggplot,Chromatogram` and `ggplot,Chromatograms`?).

@sgibb @lgatto  any comments/suggestions?

**Comment by lgatto** [comment]
Yes, I like this idea, especially that this allows to create interactive plots with the same infrastructure.

A few questions/comments:

- Maybe there's a need for `as(chromatogram, "data.frame")` and  `as(chromatograms, "data.frame")`. The format of these data.frames should match the internal representation, which seems be be the long form anyway. That's a function that would be needed to use `ggplot2`, but is generally also very useful in my opinion. 

I don't think there's anything like `ggplot,Chromatogram[s]`, as it's not a method. It would be cool of we could actually type `ggplot(data = chrom, aes(x = bpi, y = rt, colour = sample) + geom_line()`, but I don't think that would be possible. 

I see that @stanstrup named his function `ggplotChromatograms`. I would prefer to keep a simple verb/generics-like syntax that works across all objects:
 
- we could have simple convention for all the `ggplot2`-based plotting, and use a generic `gplot`; users can either `plot(chrom)` or `gplot(chrom)` at will. 
- or have an `MSnbase`-wide option that defines the plotting backend: something link `setMSnbasePlotting("ggplot2")` and `setMSnbasePlotting("graphics")`, which controls `plot(chrom)`. Note that this doesn’t require to have both implementation; if there's no `ggplot2` implementation, `plot()` defaults to whatever is available.

In other places in `MSnbase` there's a mix of both plotting infrastructure. At times, I would prefer to have the other at hand too, hence my suggestions above.

**Comment by stanstrup** [comment]
The function `.ChromatogramsLongFormat` I wrote (https://github.com/stanstrup/xcms_ggplot2/blob/master/ggplot.Chromatograms.Rmd) basically does what you want as(chromatograms, "data.frame") to do. If `pdata`  is carried over to `chromatogram` objects the remaining data wrangling I did can be moved from the plotting function to the function that makes the long format.

That way the only code left to do a nice plot is

```r
p <- ggplot(data = bpis_long, aes(x = `Retention time`, y = intensity, text = text, group = interaction(fromFile,mz_interval))) + 
                geom_line() +
                theme_classic() +
                labs(x = x_lab, y = "Intensity")
```

So you might indeed consider not having a plotting function at all but just a function to convert to the long format needed.
I guess the idea was to do ggplot2 versions of more plotting functions though so I don't know what the most consistent way would be.

The only reason I didn't implement it as a method is just that I have never methods before so would need to learn how. I thought better figure if anyone wanted the plots first.

I really don't like the "MSnbase-wide option" option. Seems like a mess to me and confusing to many people.


Btw.: I think it would be good to have @filterRt too. Otherwise how do you distinguish intervals with same mz range but different Rt range?

**Comment by lgatto** [comment]
I did see the `.ChromatogramsLongFormat` function. It would be good to export the standard coerce syntax for all our objects, which is `as(from, to)` (S4) and `as.to.from` (S3). 

> I think it would be good to have `@filterrt` too. Otherwise how do you distinguish intervals with same mz range but different Rt range? - Cc @jotsetung 

I would also rather tend to prefer a `gplot` method for `ggplot2`-implementations and `plot` for `graphics`-based implementations. The only very minor downside is that currently, some plot use `ggplot2`.

**Comment by jotsetung** [comment]
I would also go for the `gplot` function.

re. `@filterrt`: each row in a `Chromatograms` object is supposed to be for a different `rt` and/or `mz` range. We could distinguish them by that. If you have them in a `list` there's obviously no way to group/separate them neatly. I'll think over it.

Including the phenoData is on its way...

**Comment by lgatto** [comment]
Any news on this?

**Comment by stanstrup** [comment]
So no. haven't got any further. I will try to get something done on this this week with the @phenoData that has been carried over and proper scan IDs.

**Comment by lgatto** [comment]
No hurry, just checking - thanks in advance.

**Comment by etrh** [comment]
I was wondering if there's been any progress with this so far?

I've been trying to generate interactive `BPC` and `TIC` plots (using Plotly), but to no avail. Is anyone aware of a straight-forward way to generate interactive plots out of `Chromatograms` objects?

**Comment by jotsetung** [comment]
No, sorry. Haven't had any time for that.
