### ISSUE TITLE
Identification data filtering prior to addition to MSnExp/MSnSet

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#241]
This is a follow up from #235, that deals specifically with identification data filtering. Default filtering will do the following:
- keep only rank 1 peptides
- remove decoy hits
- keep only unique (proteotypic) peptides

Another important point is that `calculateFragments` can't handle `PEPTIDESEQUENCE1;PEPTIDESEQUENCE2` as input, which will have to be addressed for multi-protein hit peptides and peptides with multiple modifications, although in such cases the sequence might actually be the same.

See also #232

**Comment by lgatto** [comment]
See new [`filterIdentificationDataFrame`](https://github.com/lgatto/MSnbase/blob/master/R/functions-addIdentificationData.R#L58-L91) function.

**Comment by sgibb** [comment]
Just a minor point. This function will fail for `decoy=NULL` and `verbose=TRUE` in the *rank* if-block because `n1` is missing. Same for the other *n* values.

Am 7. August 2017 14:22:37 MESZ schrieb Laurent Gatto <notifications@github.com>:
>Closed #241.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/lgatto/MSnbase/issues/241#event-1195302281

-- 
Sent from my mobile device. Please excuse my brevity.

**Comment by lgatto** [comment]
Yep, thanks!
