### ISSUE TITLE
Update the .header and header,pSet methods?

### ISSUE THREAD

**Issue by jorainer** [lgatto/MSnbase#254]
Implementing the code to enable export of `MSnExp`/`OnDiskMSnExp` to mzMLmzXML files I came across the `heaader,pSet`/`.header` function (https://github.com/lgatto/MSnbase/blob/master/R/utils.R#L402:L438).

Now, I've implemented the `.spectrum_header` that returns a `numeric` with the header information for one `Spectrum` (https://github.com/lgatto/MSnbase/blob/writeMSData/R/functions-Spectrum.R#L537:L569). The advantage over this function over the `.header` function is that it could be applied using `lapply` to all spectra in an object. This would be faster then the individual `lapply` calls for each column that is performed in `.header`.

Only big difference/problem is that the names of `spectrum_header` are the same than the ones one gets by calling `mzR::header` (e.g. `"acquisitionNum"`) while the `.header` function returns a `data.frame` with e.g. `"acquisition.number"`. This is also related to issue #243 .
Also, the `.header` does not return all header arguments in the present form - some columns are missing.

Should we change this? @lgatto @sgibb , any ideas/comments?

**Comment by lgatto** [comment]
I am happy to amend the code to make use of  `spectrum_header` and harmonise the infrastructure, especially if that helps with #243. There will be some wider side effects with things breaking due to changes in feature variable names, but should be worth it. 

There might also be some side effects in terms of caching (see `cache.R` and old data), but I am happy to help out with these.
