### ISSUE TITLE
change rt() to rtime() in the The "Spectrum" Class webpage

### ISSUE THREAD

**Issue by pavel-shliaha** [lgatto/MSnbase#277]
The function to extract retention time for a spectrum is called rt() in the documentation for The "Spectrum" Class, but it is in fact called with rtime().

**Comment by sgibb** [comment]
I guess you refer to the following page: https://lgatto.github.io/MSnbase/reference/Spectrum-class.html

There you could find `rt` in the *Slots* section (because the internal slot of the S4 class `Spectrum` is called `rt`):

<img width="514" alt="screenshot_20171122_214100" src="https://user-images.githubusercontent.com/1828443/33148931-fd703c60-cfcd-11e7-93f2-0be94e8f730d.png">

Here you find `rtime` in the *Methods* section because the method to extract `rt` is called `rtime` (`rt` was already defined in `stats` for the students t distribution):

<img width="520" alt="screenshot_20171122_214254" src="https://user-images.githubusercontent.com/1828443/33148966-2040c034-cfce-11e7-8af9-d64d56b63deb.png">

IMHO the documentation is correct.

**Comment by pavel-shliaha** [comment]
yes. Sorry, my mistake.
