### ISSUE TITLE
Error when using medpolish for quantification

### ISSUE THREAD

**Issue by jgriss** [lgatto/MSnbase#327]
Hi,

I found that when I use 
```r
combineFeatures(qnt.norm, groupBy = fData(qnt)$accession, fun = "medpolish", verbose = T)
```
the function fails with the error
```
Error in if (converged) break : missing value where TRUE/FALSE needed
```

This seems to be a known issue with the `medpolish` function of the `stats` package (http://r.789695.n4.nabble.com/bug-fix-integer-overflow-in-medpolish-function-td4747770.html)

Would it be possible to add the proposed fix (using `as.numeric` before calling `medpolish`) to MSnbase?

Thanks a lot!

Johannes

**Comment by lgatto** [comment]
I had this exact same discussion with Ludger. The short answer is no, it's not as simple as `medpolish(as.numeric(x))`. The longer answer is that `medpolish` produces an overflow.

The reason this happens is because the data are integers. Using `as.numeric` converts them to doubles, which prevents the overflow. Before suggesting a quick fix, it is interesting to see when/why it happens. In an example data called `x` I looked at when investigating the issue, it happens for a specific protein group `P00358;P00359;P00360`.

```r
 grp <- fData(x)$Proteins
 k <- grp == "P00358;P00359;P00360"
 xx <- exprs(x[k, ])
 medpolish(xx)
```

Removing remove one feature to avoid the overflow would make it work

```r
 medpolish(xx[-1, ])
```

A solution is to revert to a `double`:

```r
## change the expression data to double
x2 <- x
tmp <- matrix(as.numeric(exprs(x2)), ncol = ncol(x2), nrow = nrow(x2))
rownames(tmp) <- featureNames(x2)
colnames(tmp) <- sampleNames(x2)
exprs(x2) <- tmp

## this works
combineFeatures(object = x2, fun = "medpolish",
                groupBy = fData(x2)$Proteins,
                na.rm = TRUE, maxiter = 20L)
```

As a conclusion to this, it might be worth considering having a function that changes the expression data from integer to double (essentially a wrapper to the 4 lines above) and advise users to run it if they encounter an overflow.

**Comment by jgriss** [comment]
Thanks for the quick response! I'll use your solution right away!

And sorry, I was hoping there'd be an easy fix!

**Comment by lgatto** [comment]
Well, there could be an easy conversion inside `combineFeatures`, but I am not sure that is a good thing to do. But as you are the second person to report it, it might be worth considering. Please follow up here if it comes up again so that I can keep track of it and invest some time when possible. 

Thank you for your interest in using `MSnbase`.
