### ISSUE TITLE
addIdentificationData does not merge "reduced" spectra

### ISSUE THREAD

**Issue by franciscodavid** [lgatto/MSnbase#346]
I have found that the `reduce` method used in `add*IdentificationData` functions causes a problem when trying to merge spectra and identification data through `utils.mergeSpectraAndIdentificationData` that results in identification data loss.

`reduce() ` also concatenates fields in `icol` for the records with the same spectrumID. For instance spectrumFile becomes something like: 'file1;file1;file1'. This causes unmatches when trying to `utils.leftJoin` featureData and the reduced dataframe.

As a proposed solution I thought about not reducing `icol` columns, then merging works without data loss. BUT isDecoy column for those records becomes something like 'FALSE;FALSE;FALSE', which is unnecessary and converts boolean data into characters. (At this step, decoy data has been discarded already). I think similar problems could arise across other columns in the identification dataframe, where we end up with redundant concatenated data.

I encountered this problem dealing with a phosphoproteomics dataset, where several peptide modifications coincide in the same spectrumID (therefore are reported in separate records by mzR) and are lost from the dataset when identification data is merged with the MSnExp object.

**Comment by lgatto** [comment]
Thank you for your input. Also tagging @sgibb here.

Could you show more details to or share a small file to help me visualise your use-case a bit more. From what I understand, having an option to not reduce on `icol` and sort out `isDecoy` (using boolean operations, for example) would fix the problem you observe - would this be indeed the case?

**Comment by sgibb** [comment]
@franciscodavid thanks for reporting this problem. Indeed `reduce` can cause harm to `utils.leftJoin` here. As a quick fix I would suggest to add an `exclude` argument to `reduce` that is passed to `utils.vec2ssv.data.frame`. All `.addIdentificationData*` should exclude the `fcol` and `icol` in `reduce` (as you already suggested). In a perfect world there won't be duplicated filename/aquisitionnum combinations and so it should not create false matches but avoid the above problem (but we know the proteomics software and file formats are far from being perfect).

The `isDecoy` problem is different. In general we could test in `utils.vec2ssv` if all elements are the same and reduce something like `FALSE;FALSE;FALSE` to `FALSE`. But this will make the inverse function (`utils.ssv2vec`) a little bit harder and both functions slower. But even then we would end with a `character` instead of a `logical` if just one row has a non-unique entry. If we use boolean operations we loose some information. The current approach keeps all information but converts everything to character. We could prepend an identifier for the vector class/type so `utils.ssv2vec` would be able to recreate the original vector, e.g. `L;FALSE;FALSE;FALSE`, `I;1;2`, `C;file1;file2` (this change would break some code, at least in `synapter`).

Or we could avoid `utils.vec2ssv` completely because a `data.frame` (is just a list and) can store (sub)lists in columns (I don't like this approach and I guess this would break even more code).
