### ISSUE TITLE
confusing parameter `tolerance` and `relative` documentation in plot and calculateFragments

### ISSUE THREAD

**Issue by floraliu1011** [lgatto/MSnbase#350]
Hi,

I'm new to MSnbase and when I was trying to plot a spectra with ion annotation using the `plot(spectrum, peptide_sequence,...)` function, I was having some trouble understanding the parameter `tolerance ` and `relative` in the argument. 

I thought that `tolerance` should be an argument passed in to `calculateFragments` from the `plot` function but while the default value of tolerance is set to 25e-6 in `calculateFragments` but it is set to 0.1 in `plot`.  So are those two parameter different in any ways? And which one would be a reasonable value to use?

And the documentation of parameter `relative ` is also a bit confusing to me, too. What is it *relative* to? Is it relative to m/z for each peak in the spectra? And can I get an annotation with ppm based mass tolerance window by combining it with `tolerance` value? E.g. If I want 20ppm mass tolerance I need to use `tolerance = 20e-6, relative = TRUE`, is that correct?

**Comment by sgibb** [comment]
I am sorry I didn't write the documentation more clearly. 

> ... `tolerance` is set to `25e-6` in `calculateFragments` but it is set to `0.1` in `plot`. So are those two parameter different in any ways?

The `tolerance` argument has different meanings in different contexts (maybe that is not good). Historically it was introduced to mark common peaks if you plot two spectra against each other. Later we added the `calculateFragments` method (that has its own `tolerance` argument) and extend the `plot` method to show fragment annotations as well. Now `tolerance` has more or less two meanings depending what you want to plot. 

Why we choose `tolerance=0.1` as default (and `relative=FALSE`)? To be honest I don't know anymore. It doesn't seem to make any sense because `compareSpectra` and `calculateFragments` (both underlying functions that use the `tolerance` and `relative` argument) have `tolerance=25e-6` (`relative=TRUE`) as default. Thanks for reporting this!
(Just as hint: internal both methods use the same matching function. So technical both arguments `tolerance` and `relative` have always the same meaning.)

@lgatto: IMHO we should change the `tolerance=0.1` to `tolerance=25e-6` in all plotting functions. Do you agree? And `relative=FALSE` to `relative=TRUE` (same problem).

> And which one would be a reasonable value to use?

The `tolerance` argument depends on the resolution of your instrument/data.

> `relative` is also a bit confusing to me, too. What is it *relative* to?

While its confusing you got it right. `relative == FALSE` (absolut) means that we treat *mz* values as positive match if they fall in `target-mz +/- tolerance`. For `relative == TRUE` they have to fall into `target-mz +/- target-mz * tolerance`.

> If I want 20ppm mass tolerance I need to use `tolerance = 20e-6`, `relative = TRUE`, is that correct?

Yes.

JFTR: from `?calculateFragments`

>  The ‘...’
          arguments are passed to the internal functions.  Currently
          ‘tolerance’, ‘method’ and ‘relative’ are supported.  You
          could change the ‘tolerance’ (default ‘25e-6’) and decide
          whether this tolerance should be applied relative (default
          ‘relative = TRUE’) or absolute (‘relative = FALSE’) to match
          the theoretical fragment MZ with the MZ of the spectrum.

**Comment by lgatto** [comment]
> @lgatto: IMHO we should change the tolerance=0.1 to tolerance=25e-6 in all plotting functions. Do you agree? And relative=FALSE to relative=TRUE (same problem).

Yes, consistency is key. PR welcome.

**Comment by floraliu1011** [comment]
Thanks for your quick response, it makes much more sense now.

Maybe I can just go ahead and fix this real quick if you don't mind since I've been studying the source code for a while lol

**Comment by lgatto** [comment]
Yes, @floraliu1011, that would be great. Feel free to send a pull request and @sgibb or myself will review it and merge.

**Comment by floraliu1011** [comment]
#353 #352 #351
