### ISSUE TITLE
Warnings on Windows 

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#371]
```
Found the following significant warnings:
  Rd warning: C:/Users/biocbuild/bbs-3.8-bioc/tmpdir/RtmpoDKv8N/R.INSTALL1ddc6a06ea8/MSnbase/man/MSnExp-class.Rd:243: file link 'isolationWindow' in package 'mzR' does not exist and so has been treated as a topic
  Rd warning: C:/Users/biocbuild/bbs-3.8-bioc/tmpdir/RtmpoDKv8N/R.INSTALL1ddc6a06ea8/MSnbase/man/MSnSet-class.Rd:510: file link 'write.exprs' in package 'MSnbase' does not exist and so has been treated as a topic
  Rd warning: C:/Users/biocbuild/bbs-3.8-bioc/tmpdir/RtmpoDKv8N/R.INSTALL1ddc6a06ea8/MSnbase/man/OnDiskMSnExp-class.Rd:489: file link 'normalize' in package 'MSnbase' does not exist and so has been treated as a topic
  Rd warning: C:/Users/biocbuild/bbs-3.8-bioc/tmpdir/RtmpoDKv8N/R.INSTALL1ddc6a06ea8/MSnbase/man/chromatogram-MSnExp-method.Rd:70: file link 'Chromatogram' in package 'MSnbase' does not exist and so has been treated as a topic
  Rd warning: C:/Users/biocbuild/bbs-3.8-bioc/tmpdir/RtmpoDKv8N/R.INSTALL1ddc6a06ea8/MSnbase/man/combineFeatures.Rd:49: file link 'NTR' in package 'MSnbase' does not exist and so has been treated as a topic
  Rd warning: C:/Users/biocbuild/bbs-3.8-bioc/tmpdir/RtmpoDKv8N/R.INSTALL1ddc6a06ea8/MSnbase/man/combineFeatures.Rd:156: file link 'NTR' in package 'MSnbase' does not exist and so has been treated as a topic
  Rd warning: C:/Users/biocbuild/bbs-3.8-bioc/tmpdir/RtmpoDKv8N/R.INSTALL1ddc6a06ea8/MSnbase/man/estimateNoise-method.Rd:45: file link 'estimateNoise' in package 'MALDIquant' does not exist and so has been treated as a topic
See 'C:/Users/biocbuild/bbs-3.8-bioc/meat/MSnbase.Rcheck/00install.out' for details.
```
@sgibb @jotsetung - I'll look into #367 now, but also saw the [warnings above on Windows](https://bioconductor.org/checkResults/devel/bioc-LATEST/MSnbase/tokay1-checksrc.html). In case you know how to fix these, please let me know.

**Comment by jotsetung** [comment]
I'll have a look at these.

**Comment by sgibb** [comment]
I had the same issue on `topdownr`. It is caused by wrong links generated by `roxygen2` if you use the markdown syntax. We have to link against the **name** of the manual page (and not against an alias).
E.g. I had a warning for:
```r
[MSnbase::calculateFragments()]
```
which could be fixed by:
```r
[`MSnbase::calculateFragments()`][MSnbase::calculateFragments-methods]
```
The format `[link text][link target]`. Please note that *link text* is not typeset as code. That's why we need to add ` here.

For the `MALDIquant` warning it should be:
```r
[`MALDIquant::estimateNoise()`][MALDIquant::estimateNoise-methods]
```

**Comment by sgibb** [comment]
Oh, I see the same is true if you don't use `roxygen2` at all (e.g. the MALDIquant part seems to be in `pickPeaks.Rd`). In that case the correct format is:
```r
\code{\link[MALDIquant:estimateNoise-methods]{MALDIquant::estimateNoise()}}
```

I can't fix it right now. Maybe tonight.

**Comment by jotsetung** [comment]
I have a hard time reproducing the warnings above. On my Windows build system (R-3.5.1) I don't get any warnings. Will check if they/I have a special setup.

**Comment by sgibb** [comment]
I did all the changes but can't run `roxygenise` because `pkgload` throws the following error:

> Error in add_classes_to_exports(ns = nsenv, package = package, exports = exports,  : 
  in ‘MSnbase’ methods for export not found: reduce

Simply adding `@export` to `reduce,data.frame-methods` in utils.R doesn't solve the problem. 
(It is the same error that prevents `pkgdown::build_site()` to run successfully on travis.)

Please see the https://github.com/lgatto/MSnbase/tree/man branch.

**Comment by sgibb** [comment]
@jotsetung Which remaining problems? The https://github.com/lgatto/MSnbase/tree/man branch contains the fixes for all of the above warnings. But I have no idea how to run `roxygenize` to complete it (ok I could manually edit the Rd files but then we will have the problem the next time we need `roxygen2`).

**Comment by jotsetung** [comment]
Aren't the affected links all in static man pages? For these it should be OK to edit the Rd files as they will not be replaced running `devtools::document()` on the package. Or am I missing something?

Re remaining problems: I checked the `man` branch on Windows but still got some warnings.

**Comment by sgibb** [comment]
> Aren't the affected links all in static man pages?

At least `man/chromatogram-MSnExp-method.Rd` is generated by `roxygen2::roxygenise`/`devtools::document`.

I found some unicode characters in `R/utils.R` that cause the error in `roxygenise`: https://github.com/lgatto/MSnbase/commit/6be3d77a30843295fa6db44a4365e0c2d154d872

Now it is working again (`pkgdown::build_site()` is also working now! and travis runs successful, too :tada:)

@jotsetung I don't have a windows build machine currently. I just addressed the WARNINGs @lgatto posted above. Hopefully the fix is working (at least it doesn't generates ERROR/WARNINGs on linux). Do you refer to the g++ compiler warnings (unused variables/functions?). I didn't want to touch these warnings because I am not familiar with the code. So if you would review these warnings it would be great.

**Comment by jotsetung** [comment]
Nice @sgibb! I'll check on my Windows build machine.

**Comment by jotsetung** [comment]
All warnings are gone now on my Windows build machine! 🎉

**Comment by lgatto** [comment]
Thanks - pushed to Bioc.
