### ISSUE TITLE
hdf5 backend

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#387]
This issues documents my exploration of hdf5 to possibly implement an on disk read/write backend for `MSnExp` objects.

**Comment by lgatto** [comment]
A first question for @grimbough 

Am I correct in understanding that 

```r
mz5 <-  H5Fopen(h5f)
mz5$grp1$file1
mz5$grp1$file2
mz5$grp2$file1
mz5$grp2$file2
...
```
will be faster than 
```r
h5read(h5f, "grp1/file1")
h5read(h5f, "grp1/file2")
h5read(h5f, "grp2/file1")
h5read(h5f, "grp2/file2")
...
```
as the latter will open/close every time?

If so, is it possible to use the former approach programmatically, if I have a character containing `grp1/file1`, a syntax like the second approach.

**Comment by lgatto** [comment]
Another question for @grimbough 

At the end of section 5.2 *Writing data to an HDF5 file*, the close functions for datasets, dataspaces, and files are shown. Assuming I want to close everything, can I just close the file and will the lover level structures be closed automatically?

**Comment by grimbough** [comment]
`h5read()` can actually take a file handle instead of a character string, so you can do something like:

```
mz5 <-  H5Fopen(h5f)
h5read(mz5, "grp1/file1")
...
H5Fclose(mz5)
```

Then you only have to open the file once (this is pretty much what the `$` operator is doing internally).  

I can't remember how many 'files' you might have in total, but it will probably have to be quite high before you notice the overhead in repeatedly opening the file.  Out of curiosity I here's an example where we write out 20 matrices, each of dimension 10,000 x 2, and then read using the two strategies:

```
library(rhdf5)

## generate data and write to file
mat <- matrix(runif(n = 200000), ncol = 2)
h5f <- tempfile(fileext = ".h5")
if(file.exists(h5f)) 
  file.remove(h5f)
h5createFile(h5f)
for(i in seq_len(2000)) {
  h5write(mat, file = h5f, name = paste("dset", i, sep = "_"))
}

## open file each time
f1 <- function() {
  dsets <- h5ls(h5f)$name  
  for(d in dsets) {
    h5read(file = h5f, name = paste0("/", d))
  }
}

## open file once and pass handle
f2 <- function() {
  dsets <- h5ls(h5f)$name  
  mz5 <- H5Fopen(h5f)
  on.exit(H5Fclose(mz5))
  for(d in dsets) {
    h5read(file = mz5, name = paste0("/", d))
  }
}

## benchmark
bm1 <- microbenchmark::microbenchmark(f1(), f2(), times = 25)
```

```
> bm1
Unit: milliseconds
 expr      min       lq     mean   median       uq      max neval
 f1() 201.4870 213.5601 227.0688 221.3914 230.1207 327.2722    25
 f2() 191.8352 204.0992 228.3481 211.3808 235.3679 373.6531    25
```

If I make 2000 datasets instead, here are the timings:

```
> bm1
Unit: seconds
 expr      min       lq     mean   median       uq      max neval
 f1() 25.70436 25.86346 26.25354 25.95598 26.01461 27.72929     5
 f2() 23.07560 23.27704 23.46852 23.61865 23.63371 23.73760     5
```

---

Regarding the second question, you have to explicitly close each of them.  I tend to put  the close functions inside `on.exit()` so even if a function crashes references should get cleared up.  You can also use `h5closeAll()`, but that is very heavy handed and will close everything created in that R session, even outside the current scope. 

Might also be worth noting that things don't need to be closed in the order you open them, so if you never need a file reference again you can close it even if you're using a dataset reference inside it, e.g the following will get the dimensions of the first dataset in the example created earlier, even though we close the file reference.

```
fid <- H5Fopen(h5f)
did <- H5Dopen(fid, name = "dset_1")
H5Fclose(fid)
sid <- H5Dget_space(did)
H5Dclose(did)
dim <- H5Sget_simple_extent_dims(sid)
H5Sclose(sid)
```

**Comment by lgatto** [comment]
Thank you @grimbough - that should get me going for a while!

**Comment by lgatto** [comment]
Hello @jotsetung and @sgibb - here's a first preview at the `hdf5` backend:

Reading the data into the `hdf5` backend is slower as it first reads the data as an `OnDiskMSnExp`, then writes the raw spectra data into a hdf5 file:

```r
 > system.time(x <- readHdf5DiskMSData(fls))
   user  system elapsed 
129.992   1.260 130.727 
> system.time(y <- readMSData(fls, mode = "onDisk"))
   user  system elapsed 
 20.465   0.589  20.608 
```
But after that, the gains look impressive:
```r
> microbenchmark(x[[1]], y[[1]], times = 10)
Unit: milliseconds
   expr        min         lq       mean     median         uq        max neval cld
 x[[1]]   10.08535   11.61323   13.01642   12.58071   13.56123   19.37109    10  a 
 y[[1]] 2189.87442 2229.69491 2254.71639 2255.77197 2291.45785 2308.98109    10  b
```
This needs further testing, and see how `readHdf5DiskMSData` scales for bigger data, but looks promising so far.

**Comment by lgatto** [comment]
@grimbough - could you comment on parallel reading/writing hdf5 files. For example, I have 
```
     group     name       otype dclass       dim
0        /        1   H5I_GROUP                 
1       /1 F1.S0001 H5I_DATASET  FLOAT 25800 x 2
2       /1 F1.S0002 H5I_DATASET  FLOAT 25934 x 2
3       /1 F1.S0003 H5I_DATASET  FLOAT 26148 x 2
...
7534        /        2   H5I_GROUP                 
7535       /2 F2.S001 H5I_DATASET  FLOAT 43527 x 2
7536       /2 F2.S002 H5I_DATASET  FLOAT   211 x 2
7537       /2 F2.S003 H5I_DATASET  FLOAT   124 x 2
...
```
with potentially 10s or 100s of groups.

- Could I write these groups in parallel, and would this be faster?
- Could I read these groups in parallel, and would this be faster?

**Comment by jotsetung** [comment]
@lgatto, what are the timings if you extract a random spectrum (not the first) from the files?

Question: how about having a dedicated `HDF5MSnExp` object?
- `OnDiskMSnExp` uses the raw files as backend (*mzML* etc)
- `MSnExp` has all the data in memory
- `HDF5MSnExp` uses HDF5 as a backend.

Having a `setAs("OnDiskMSnExp", "HDF5MSnExp")` would then read all spectra and write them into a HDF5 file. Or `readMSData` could have a third `mode` `"hdf5"`.

In case, I could also give a hand in the implementation - looks like fun :).

**Comment by lgatto** [comment]
See the [hdf5 project](https://github.com/lgatto/MSnbase/projects/1) for this development branch.
