### ISSUE TITLE
Writing updated data to hdf5 file(s)

### ISSUE THREAD

**Issue by jorainer** [lgatto/MSnbase#405]
With the hdf5 backend we have the possibility to write/update the records in the hdf5 file(s) after data manipulation operations.

Since `Hdf5MSnExp` extends `OnDiskMSnExp` it uses it's lazy execution capabilities. So, any manipulations are applied on-the-fly each time data is extracted. I like that approach and am a little reluctant to change `Hdf5MSnExp` to write changes to disk for each operation that is performed. My suggestion would be to use lazy execution also for `Hdf5MSnExp` and have a `consolidate` function/method that updates the data in the hdf5 file(s) with any data manipulation and filtering operations. 

@lgatto any thoughts on this?

By the way, another *benefit* from the lazy execution would also be that we could have an `undo` function that simply deletes the latest, or a specific, data processing step from the `@processingQueue` and so undoing a data manipulation.

**Comment by lgatto** [comment]
My idea was the following:
- For most operations, as we have them now, we use lazy execution as for the `OnDiskMSnExp` back-end. That's should also be the first aim of the new back-end, making sure it behaves like `OnDiskMSnExp` and we can demonstrate some speed gains.
- There will need to be a function to `apply` the lazy processing queue and, rather than instantiating the processed data on-the-fly, updates the data on disk.
- Some operations, like merging of spectra produce data in memory - in such a case, we would need a function that explicitly says to dump that data back to disk and update/overwrite the hdf5 data, or even write it to new files.

**Comment by jotsetung** [comment]
OK, so we basically agree on it.

**Comment by jotsetung** [comment]
A note so far: doesn't seem that we can simply overwrite existing datasets within an hdf5 file if it does not have exactly the same dimensions. So it seems that we have to either empty the hdf5 file before writing updated spectra to it, or we delete the file and re-create it. This would also work if we're e.g. filtering the object by retention time or spectra.

**Comment by lgatto** [comment]
We could even, under certain conditions, write data to a temporary directory, irrespective of what the user asks. And if there's a request to *consolidate*, check what hasn't been written yet, complete what still needs to be done, and then copy the files in the user's directory.

**Comment by jotsetung** [comment]
We could. But note that writing the hdf5 takes quite some time, and we would have to implement a way to keep track what has been written and what not. 

For starters I would implement the *simple* approach of having the `OnDiskMSnExp` lazy execution approach and save once the user calls `consolidate`.

I just compared the performance of emptying an hdf5 file and re-filling it with deleting the hdf5 file and re-creating and filling it with data. There's no difference in performance, so we can use either approach.

**Comment by lgatto** [comment]
I said it was possible, I never said it would be easy... But yes, we will start with a simple approach. 

However, given that writing takes time, writing in smaller chunks (possibly in the background), when the data is anyway requested by the user (i.e. processed on the fly), might prove a winning strategy.

**Comment by jotsetung** [comment]
Seems it is not possible to have parallel processes **writing** to the **same** hdf5 file:

I create an hdf5 file with two groups *a* and *b*. The `.h5write_spectra_clean_file` is supposed to be used to update the content for one group, i.e. to replace its content with the newly provided data.

```r
library(rhdf5)
library(BiocParallel)

## Generate the "data"
a <- lapply(1:1000, function(x) matrix(rnorm(20000), ncol = 2))
b <- lapply(1:1000, function(x) matrix(rnorm(20000), ncol = 2))
names(a) <- as.character(seq_along(a))
names(b) <- as.character(seq_along(b))

h5g_file <- tempfile()
## Fill with data.
h5 <- H5Fcreate(h5g_file)
h5createGroup(h5, "a")
h5createGroup(h5, "b")
for (i in seq_along(a)) {
    h5write(a[[i]], h5, paste0("a/", i))
}
for (i in seq_along(b)) {
    h5write(b[[i]], h5, paste0("b/", i))
}
H5Fclose(h5)

## Function to replace an hdf5 group.
.h5write_spectra_clean_file <- function(h5file, spectra, group = "a") {
    h5 <- H5Fopen(h5file)
    on.exit(invisible(H5Fclose(h5)))
    h5delete(h5, group)
    h5createGroup(h5, group)
    for (i in seq_along(spectra)) {
        h5write(spectra[[i]], file = h5,
                name = paste0(group, "/", names(spectra)[i]))
    }    
}

## Now *replace* the content with only 500 *spectra* for each group
bpmapply(list(a[1:500], b[1:500]), c("a", "b"), FUN = function(sps, grp) {
    .h5write_spectra_clean_file(h5file = h5g_file, sps, grp)
}, BPPARAM = SerialParam())
[[1]]
NULL

[[2]]
NULL

## The same with parallel processing:
bpmapply(list(a[1:500], b[1:500]), c("a", "b"), FUN = function(sps, grp) {
    .h5write_spectra_clean_file(h5file = h5g_file, sps, grp)
}, BPPARAM = MulticoreParam(2))
Error: BiocParallel errors
  element index: 2
  first error: HDF5. File accessibilty. Unable to open file.
```

**Comment by jotsetung** [comment]
**Update**: just realized that it would work with `h5disableFileLocking()` - but somehow not consistently:

```r
> microbenchmark(
+ bpmapply(list(a[1:500], b[1:500]), c("a", "b"), FUN = function(sps, grp) {
+ .h5write_spectra_clean_file(h5file = h5g_file, sps, grp)
+ }, BPPARAM = SerialParam()),
+ bpmapply(list(a[1:500], b[1:500]), c("a", "b"), FUN = function(sps, grp) {
+ .h5write_spectra_clean_file(h5file = h5g_file, sps, grp)
+ }, BPPARAM = mcp2),
+ times = 3
+ )
Error: BiocParallel errors
  element index: 1
  first error: HDF5. Links. Can't delete message.
```

So, to be on the safe side I'd opt for the one-file per mzML/sample approach.

**Comment by lgatto** [comment]
Yes, indeed. My comment above was considering that we have 1 hdf5 file per mzML file.

**Comment by jotsetung** [comment]
I've now implemented a `consolidate` function for `Hdf5MSnExp` objects. This function reads all spectra for each hdf5 file, applies all lazy processing steps and writes the data again to the hdf5 file. In fact it replaces the content of the hdf5 file. Since it is doing this on a per-file basis, memory requierment is manageable **and** it is by default also parallelized.

Now the caveats:

Imagine this example, `data` being an `Hdf5MSnExp`:
```r
data_filt <- filterRt(data, rt = c(10, 50))

## Can still use data_filt and data:
length(spectra(data_filt))
[1] 288

length(spectra(data))
[1] 1862
```
Note that both variables, `data` and `data_filt`, link to the **same** hdf5 files. When we call `consolidate` on `data_filt`, the hdf5 files will be re-written. After that it is no longer possible to use `data` as the content in the hdf5 files changed. In fact, the hdf5 files contain after `consolidate` only the data from the spectra to which we subsetted `data`.

```r
consolidate(data_filt)

length(spectra(data_filt))
[1] 288

length(spectra(data))
Error: BiocParallel errors
  element index: 1, 2
  first error: HDF5. Dataset. Can't open object.
```
The spectra that `spectra(data)` wants to extract are simply no longer present in the hdf5 files and thus the error.

So, that's something I didn't think before, but definitely something we have to keep in mind. Basically, I would limit the use of `consolidate` only in special circumstances, i.e. if data manipulations are applied that are computational intense (such as `smooth` and `pickPeaks`).

**Comment by lgatto** [comment]
Yes, that is an issue. As mentioned on slack,  I would suggest to call such a function something more obvious, like `writeHdf5Data`, and drop the assignment.
The following could help

**Comment by lgatto** [comment]
Or, we write the *consolidated* data the new hdf5 files.

**Comment by jotsetung** [comment]
I think users should use the consolidate function rarely, but I agree .

One important thing: the assignment (if you mean replacing the orignal object) is crucial: imagine the following:

```r
data <- pickPeaks(smooth(data))
## peak picking and smoothing will be done on-the fly.

## consolidate, i.e. smooth, pick peaks and write/update the data into the hdf
consolidate(data)

```
replacing the `data` variable is actually crucial, because in `consolidate` I also remove all lazy evaluation steps. If we don't do that `spectra(data)` would read the smoothed and centroided data from the hdf5 files and apply **again** smoothing and centroiding.

**Comment by lgatto** [comment]
> replacing the `data` variable is actually crucial, because  ...

of course, I didn't mean no to, and that could be done behind the scenes. But if you think of `writeHdf5Data`, you would necessarily expect the data to be returned. I think that `updateHdf5Data` would probably be better here, as it makes it explicit that we update data that already existed, highlighting the destructive nature of the operation. 

`writeHdf5Data` could then be used to write the data into a new set of hdf5 files, if I want to keep to original data.

**Comment by lgatto** [comment]
Re `convertToHdf5MSnExp`, why not the standard `as(hdf5, mzml)` syntax? Could it be because it doesn't support extra arguments? If so, I would prefer `convertMSnExpToHdf5`, as in *convert from to*, rather than *convert to from*.

**Comment by jotsetung** [comment]
Agreed: `writeHdf5Data` -> `updateHdf5Data`. 
And you're right. I wanted to have an `as` but that doesn't allow extra arguments. Regarding the name, it should just read *convert* to an `Hdf5MSnExp`, it was not meant to be read as *convert* from `MSnExp` to `Hdf5MSnExp`. Also, at present, it supports only conversion from an `OnDiskMSnExp` to an `Hdf5MSnExp`; `MSnExp` is not supported because the `fData` does not contain all required fields.
