### ISSUE TITLE
Add hdf5 support to OnDiskMSnExp instead of having a Hdf5MSnExp?

### ISSUE THREAD

**Issue by jotsetung** [lgatto/MSnbase#407]
I have the following problem: in `xcms` I have the `XCMSnExp` object that extends the `OnDiskMSnExp` object. Now we have the `Hdf5MSnExp`, which also extends the `OnDiskMSnExp`. The hdf5 functionality of the `Hdf5MSnExp` would however also be quite useful for the `XCMSnExp` object, because it would allow a faster access to the raw data and faster extraction of identified chromatographic peaks.

My proposal/question:
- Add the hdf5 functionality to the existing `OnDiskMSnExp`, i.e. simply add the two slots `hdf5file` and `md5sum` to `OnDiskMSnExp`. If either one of these slots is missing, or they are not set, the *conventional* `OnDiskMSnExp` functionality is used, otherwise the hdf5 functionality. In the end the `Hdf5MSnExp` uses all of the `OnDiskMSnExp` functionality except of the `spectrapply` method. We could build a switch into that method to read either the data from the hdf5 file or the mzML files.

I know that's quite a bold proposal ... any comments @lgatto @sgibb ?

**Comment by lgatto** [comment]
I will need to think a bit more, but one quick question - would your suggestion not result in all methods that need to access the data to have a `if/else` block to check if it's actually and hdf5 or not.

**Comment by jotsetung** [comment]
All data access methods of `OnDiskMSnExp` go through the `spectrapply` method. We would *only* have to add an *if/else* there. The rest works out-of-the-box.

I don't know any other solution to use the hdf5 backend for the `xcms` `XCMSnExp` object. I definitely want to avoid double inheritance, i.e. having the `XCMSnExp` extending both `OnDiskMSnExp` and `Hdf5MSnExp`.

**Comment by sgibb** [comment]
Sorry, I am a little bit late to the HDF5 party. I partly followed your journey to the current state. Awesome stuff!

Regarding the implementation I am against putting an `if/else` statement into the `OnDiskMSnExp`. IMHO the HDF5 feature is a great opportunity to work on *MSnbase3* and rewrite the class hierarchy.

I would suggest a `MSnExperiment` class (would replace the current `MSnExp`) that has the well known `featureData` slot and a `backend` slot (maybe some other slots like `phenoData`, `version`, ... needed as well). The `backend` slot is of the new abstract (`VIRTUAL`) `Backend` class. The `Backend` class provides an interface similar to `DBI` (https://github.com/r-dbi/DBI) for different backends, e.g. memory, mzml, hdf5, sql, ...

I implemented a working prototype (without any checks, validation, tests, and other bells and whistles like parallelisation, processingQueue, ...; it uses matrices instead of `Spectrum` objects for simplicity and currently just supports one mzML file as source): https://gist.github.com/sgibb/54c1477d26fa8702231c447badd11776

In detail the `Backend` class offers a `backendSetup` (create files, database tables), `backendPrefill` (copy the mzML data into the backend; bad name I know), `backendReadSpectra` and `backendWriteSpectra` method. If the `MSnExperiment` want to access the spectra it just calls `backendReadSpectra` on its `backend` slot without knowing which type of backend it uses. This will make most duplication we have now (same methods with different code for `MSnExp`, `OnDiskMSnExp`) unnecessary. The backend could be specified in a constructor (see the example `readMSData` in the gist; no need for double inheritance). Also switching the backends would be easily possible (see `switchBackend` in the gist).

I know this would be a major change in our class hierarchy (worth calling it *MSnbase3*) but we could use this opportunity to integrate all the stuff we discussed before: `SpectraList` class (as in memory backend), lighter `Spectrum` objects (precursor, centroided etc. could be stored in the `mcol`/`featureData` slot).

What do you think about this suggestion?

**Comment by jotsetung** [comment]
Huh, as you say - sounds like a major rewrite. The idea is great if I get it correctly: we would only have a single object, `MSnExperiment`. To support parallel processing and everything, the backend should have something like the `spectrapply` method, that takes also the lazy processing queue and returns, as you suggest either matrices of lightweight spectra.

Given that I'll be busy with other stuff this year I would however aim first on the *cheap* approach I suggested above - and give us a little more time to design the new stuff.

**Comment by jotsetung** [comment]
Thinking it over, I even think having the `OnDiskMSnExp` supporting two backends, mzML and HDF5 is somehow similar to your approach @sgibb, only, using a single `if/else` instead of `S4` classes and method dispatching... we could also think of it as a playground for MSnbase3 😉

**Comment by jotsetung** [comment]
I really like the idea of the `MSnExperiment`. Just some things I think are important:

- we should keep the concept of the lazy processing queue. This is crucial for e.g. the *mzML* backend. I suggest to keep this as a slot in the `MSnExperiment` (or in the backend??).
- we should also re-use the concept of the `spectrapply` method. The ability to read the data on a per-file basis, apply processing steps on-the-fly and apply a function to the data (hence eventually not returning the full data) is crucial for parallel processing and large experiments.

Regarding light-weight `Spectrum` objects - I would keep the objects as they are now. I would however remove, in my eyes, unnecessary inheritances to `Versioned` objects and similar. Also I would push to make light-weight validity checks, as they really have a negative impact on performance.

What scares me a little is that we will have to implement methods multiple times, for the `MSnExperiment` and for each backend class (methods such as `filterFile` as `filterFile,MSnExperiment` will have to filter the `featureData` and the `phenoData` and `filterFile,<Backend>` the actual files, or the spectra.

**Comment by sgibb** [comment]
> only, using a single if/else instead of S4 classes and method dispatching

That's the general argument in Procedual vs OOP. But encapsulation in `S4` classes is cleaner and more future proof (if we want to add another backend, e.g. SQL)) :wink:

> we should keep the concept of the lazy processing queue

Definitely!

> we should also re-use the concept of the spectrapply method.

Definitely!

> What scares me a little is that we will have to implement methods multiple times, for the MSnExperiment and for each backend class (methods such as filterFile as filterFile,MSnExperiment will have to filter the featureData and the phenoData and filterFile,<Backend> the actual files, or the spectra.

That's nearly the same problem we have now: `filterFile,MSnExp`, `filterFile,Hdf5MSnExp`; additional `filterFile` requires a subset operator `[,MSnExp`, `[,OnDiskMSnExp`. So I don't see a real advantage for the current approach.

**Comment by sgibb** [comment]
Because you mentioned "playground" I started a "playground" branch: https://github.com/lgatto/MSnbase/tree/backends
(currently there is less functionality than in the [prototype](https://gist.github.com/sgibb/54c1477d26fa8702231c447badd11776) but at least it has a little bit of documentation.)

**Comment by jotsetung** [comment]
> That's nearly the same problem we have now: filterFile,MSnExp, filterFile,Hdf5MSnExp; additional filterFile requires a subset operator [,MSnExp, [,OnDiskMSnExp. So I don't see a real advantage for the current approach.

And having a look at the code - there are in the end not so many methods that require modifying both the `MSnExperiment` and the backend.

Re *playground*, awesome! If OK I would also jump in (with a `backends_jo` branch from which I would make from time to time pull requests to `backends`. In order to split the workload efficiently, I'd suggest we open an issue for each thing that should be implemented and assign a person to it.

**Comment by sgibb** [comment]
> If OK I would also jump in

Of course, you are welcome! I just think we should wait for @lgatto comments before wasting to much time with something he don't like.

> In order to split the workload efficiently, I'd suggest we open an issue for each thing that should be implemented and assign a person to it.

We could also group them in a "Project" (never really used that, maybe it is useful).

**Comment by lgatto** [comment]
After a first read, I think this all sounds very exciting, but like quite a bit of work. I'll keep on reading.

**Comment by jotsetung** [comment]
Closing this issue because I feel the suggestions from @sgibb and the stuff we've done in the *backends* branch are actually much better.
