### ISSUE TITLE
Add subset operator for Backend and its subclasses

### ISSUE THREAD

**Issue by sgibb** [lgatto/MSnbase#417]
- [x] `Backend` - @sgibb 
- [x] `BackendMemory` - @sgibb 
- [x] `BackendMzR` - @jotsetung 
- [x] `BackendHdf5` -

**Comment by jotsetung** [comment]
You mean `[`? Another key subsetting operator here is `filterFile`.

**Comment by sgibb** [comment]
Yep, I meant `[`, but you are right we also need `filterFile`. I would overload `[` with `i=fileIdx`, `j=spIdx`.
`filterFile,Backend` would be just `backend[fileIdx,]`.

I am wondering whether we should save the src file path in the backend instead of `MSnExperiment`. Because in `BackendMemory` can't reproduce the files from the `fileIdx` otherwise. And a subset method with `i, j, files, spectraData` argument looks awkward. 

A possible alternative would be `[i=srcFilename, j=spIdx]` (that wouldn't require src files in `Backend`).

But in fact it seems more natural that `Backend` stores the src file path instead of `MSnExperiment`, or?

**Comment by jotsetung** [comment]
Yup. I agree. having the original files in the backend makes more sense.

**Comment by jotsetung** [comment]
Question is what would make more sense, `[i, j]` with `i` being a file index and `j` a spectrum index or *vice versa*. From the usual way Bioconductor handles data matrices (columns samples, rows features) I would opt for `i` subsetting spectra and `j` subsetting files.

An implementation note for on-disk backends: subsetting by file should directly subset the `@files` slot, subsetting by spectrum would be optional (or just ignored, as for the `BackendMzR`).

**Comment by sgibb** [comment]
You are right: `i=spIdx`, `j=fileIdx/fileName` would be more bioc-like. I had the filesystem/hdf5 approach (file->spectra) in mind. In fact it doesn't matter at all. Let's go for the bioc version.

**Comment by jotsetung** [comment]
The default `[` for `Backend` simply subsets the `@files` slot based on `j`. For `BackendMzR` that is sufficient - for `BackendMemory` the spectrum index `i` should also be considered to reduce the internal list of spectra.

**Comment by lgatto** [comment]
What is the motivation for changing the semantic of `[`? It used to be `i, j = "missing", drop = "missing"`, i.e. subsetting only on spectra. Also, `[spIdx, fileIdx]` uses the matrix/dataframe convention, but violates it, as it isn't rectangular. 
- Is this really much better than `filterFile(x, 1)[[1]]`? 
- What would be the behaviour of `x[123]`? 
- And `x[[123]]`?

**Comment by jotsetung** [comment]
Well, I just thought it might be helpful to have an `[i, j]`. We have spectra as sort of *rows* and samples as *columns*. The data is not really rectangular but to me it would make sense to have `[, j]` that allows subsettings files/samples and `[i, ]` to subset the object restricing it to certain spectra.

Currently (in the *backends_jo* branch) we have:
- `[i, ]` subsets to spectra `i` and returns a `MSnExperiment`, unless `drop = TRUE` and `i` has length 1 - then a `Spectrum` is returned.
- `[, j]` subsets to samples/files `j` and returns an `MSnExperiment`.
- `[i, j]` is not supported - would be very tricky to handle.

`filterFile` simply calls `[, j]` and `[[i]]` calls `[i, ]` (with `i` being length 1).

**Comment by sgibb** [comment]
> Also, [spIdx, fileIdx] uses the matrix/dataframe convention, but violates it, as it isn't rectangular.

Important point! I have no idea what we should to with `x[1:2, 1:2]` (file 1:2 and spectrum 1:2 of each file, or spectrum 1 from file 1 and spectrum 2 from file 2?).

So maybe we should provide a `filterFile` method and the subset operator should only work on spectra level (I think that's the current behaviour for `(OnDisk)MSnExp`). So, ignore `[, j]`.
The only problem for the file-based backends would be that they need to find out in which file the spectra are, e.g. `backend[c(1, 100)]` return spectrum 1 from file 1 and (if file 1 contains 99 spectra) spectrum 1 from file 2.

**Comment by sgibb** [comment]
Why do you want to reorder the files? Wouldn't it be enough to reorder the `spectraData` `DataFrame` in `MSnExperiment` (`backendReadSpectra` will reflect these ordering)?

**Comment by lgatto** [comment]
I have thought about it, and I really think that `[i, j]` is wrong. It violates the expected semantic to filter along two equivalent dimensions, which isn't the case here. Imagine the following examples with 3 files and 1000, 900 and 800 spectra respectively - what should `x[1000, ]` return? 
- A new `MSnExperiment` with 1 spectrum?
- A new `MSnExperiment` with 1 spectrum and two empty spectra? 
- A warning, an error?

**Comment by lgatto** [comment]
If the usecase is to re-order files, then a function that does that, and `filterFile` seems to be to be the right candidate. But, like @sgibb, I am not sure what the point is? Assuming you data is like this 

| spIdx | fileIdx | ...  |
|--------|---------|-----|
| 1       | 1        | ...  |
| 2       | 1        | ...  |
| 3       | 1        | ...  |
| 1       | 2        | ...  |
| 2       | 2        | ...  |
| 3       | 2        | ...  |
| 1       | 3        | ...  |
| 2       | 3        | ...  |
| 3       | 3        | ...  |

would you goal be to get the following?

| spIdx | fileIdx | ...  |
|--------|---------|-----|
| 1       | 1        | ...  |
| 2       | 1        | ...  |
| 3       | 1        | ...  |
| 1       | 3        | ...  |
| 2       | 3        | ...  |
| 3       | 3        | ...  |
| 1       | 2        | ...  |
| 2       | 2        | ...  |
| 3       | 2        | ...  |

Could you elaborate on the reason behind this?

**Comment by jotsetung** [comment]
The `[i, j]` is now gone. In the recent commits I split that into `[i` and `filterFile` for `MSnExperiment`.

Regarding the re-ordering. I usually have larger experiments with several files that come in whatever order. Many users organize their experiment/files by sample group, i.e. in their *phenodata* file they have first the e.g. files for *KO* samples and then for *WT* samples. In a good experimental design you will however want to run the samples in a random order (never first the KO and then the WT samples). For QA (and then also to adjust for the injection order dependent signal drift) it is helpful to look at the data in that order. So I usually, after loading the experiment, order the object (`OnDiskMSnExp` or in future `MSnExperiment`) by a variable that reflects the sample injection. 

For the user the re-ordering just has to work, so if he wants to have the experiment in whatever arbitrary order he needs to be able to do that. Under the hood it is more than just re-ordering the `@spectraData` `DataFrame`: we have to re-order the files in the `@files` slot (otherwise `fileNames` would return the files in the old order), have to update the `fileIdx` in `spectraData` and re-order `sampleData`. But that's now all implemented in `filterFile,MSnExperiment`.

**Comment by jotsetung** [comment]
While implementing a `[` and a `filterFile` for the `Backend` class I found that it is not helpful at all to split the subsetting into two different functions:

`filterFile,MSnExperiment`: filters the data by file, this obviously affects also the spectra. For file-based backends it is no problem to filter just by file and remove all spectra associated with that. For `BackendMemory` it is more difficult. That backend doesn't (and shouldn't) organize spectra by file. So, implementing `filterFile` will be tricky, because all the backends needs to know is which spectra to keep.
 
`[,MSnExperiment`: filters by spectra. No problem for the `BackendMemory` because the spectrum index is passed. For file-based backends that doesn't help. They want to know which files to keep (and eventually also which spectra).

I have thus implemented a `backendSubset` method (https://github.com/lgatto/MSnbase/blob/backends_jo/R/Backend-class.R#L282-L289) that has arguments `i` and `file` and I suggest that `[,MSnExperiment` and `filterFile,MSnExperiment` pass both arguments to the backend. Which of the parameters the backend then uses has to be implemented specifically for the backend. The `BackendMemory` can ignore the `file` and just use `i`, `BackendMzR` will ignore `i` and just use `file` and `BackendHdf5` will use `file` and eventually `i`.

**Comment by sgibb** [comment]
To be honest I don't understand what should be different if we rename `[` into `backendSubset`.

I already implemented `[` and `filterFile` for `BackendMemory` yesterday. I used regular expression based on the naming scheme: `F001.S001`, `F001.S002`, ...

https://github.com/lgatto/MSnbase/blob/f6c692dbe9269cdb297a7e758ffc000adb5a4972/R/BackendMemory-class.R#L59-L85

(I see there is an `unique` missing in line 64.)

https://github.com/lgatto/MSnbase/blob/f6c692dbe9269cdb297a7e758ffc000adb5a4972/R/BackendMemory-class.R#L136-L138

IMHO we should provide a clean API and provide both methods (and not one that does both depending on its input):
- `[` selects spectra by global index: easy for `BackendMemory` (not really if we want to keep the `@files` correct).
- `filterFile` keeps all spectra from selected files: easy for file-based backends, just remove some files, harder for `BackendMemory`.

Regardless which backend we use (memory, file-based) we have to subset the spectra and files (at least for housekeeping).

**Comment by sgibb** [comment]
@jotsetung I completely understand your use case. IMHO we should provide a `reorderFiles,MSnExperiment-method` (it could use `filterFile,Backend-method` internally).

**Comment by jotsetung** [comment]
@sgibb , I don't think we need yet another function (`reorderFiles`). We can use `filterFile` for that. The name is not that intuitive, but I prefer it that way than having another function.

Regarding the `backendSubset`: there are several reasons I added this function and think it's better than `[` and `filterFile`.
1) (well, not that important), `[` and `filterFile` have generics and will get exported once the class is exported. Also, all other backend-related functions start with `backend` which I actually like, because it is clear that this is a dedicated function for the backend class.
2) more importantly: subsetting by spectrum (`[`) does not only subset by spectrum but also by file in the backend. If you have 2 files with 100 spectra each, subsetting an object to the first 50 means that you essentially restrict to file 1 and that you subset to the first 50 spectra for that file. The same is actually true if you do a `filterFile`, because that does also subset spectra (important for `BackendMemory`, not so much for the on-disk backends). Implementation of the `[,Backend` and `filterFile,Backens` are not that straight forward and it depends in which order you call them in the `MSnExperiment` object, i.e. first `[,Backend` and then `filterFile,Backend` or *vice versa*? Each call potentially changes stuff in the backend, so in the `BackendMemory`, if you call `[` it will subset spectra, if you then call `filterFile` with the indices of the files, it might be that the spectra for these files are no longer there. It's much easier and cleaner to do the subsetting in a single method -> `backendSubset`.

The advantages thus are:
- One function to call in the backend (`backendSubset`*vs* `[` followed by a `filterFile`.
- Implementation is easier in the backend class.

**Comment by sgibb** [comment]
Sorry, I thought we are talking about slightly different things but after reviewing #43 I recognize we are on the same page. The only difference is a different mind model about what belongs to the backend.
I was asking for two different functions `[` and `filterFile` for `Backend` (and you indeed wrote two different methods but for `MSnExperiment`). 
So I am fine with `backendSubset` if we could agree that it is important not to use `unique(file)` before calling `backendSubset`. Both `i` (`spectraData$spIdx`) and `file` (`spectraData$fileIdx`) have to have the same length (and `i` should not be the global index from `MSnExperiment[i,]` but the `spectraData$spIdx`) and the backend would be responsible to do the right thing. To make it clear I would rename the arguments:  `backendSubset(x@backend, fileIdx=x@spectraData$fileIdx, spIdx=x@spectraData$spIdx)` (this would be inline with our other `backend` methods, e.g. `backendReadSpectra`).

**Comment by sgibb** [comment]
Sorry, I meant `backendSubset(x@backend, spectraData=x@spectraData)` (this would be inline with our other backend methods, e.g. backendReadSpectra). Than you could use `fileIdx`/`spIdx` if you need to and for the `BackendMemory` class I could simply use the `rownames(spectraData)`.

(Maybe it would be better for me to sleep a night over it instead of writing hundreds of answers with different meanings/opinions ...)

**Comment by jotsetung** [comment]
OK, then I will rewrite the `backendSubset` as you suggested (`backendSubset(object, spectraData`). It is more consistent with our other `backend` methods, very good point.

**Comment by jotsetung** [comment]
All is implemented now and included in the pull request #430 . Feel free to close if you're happy with this @sgibb
