### ISSUE TITLE
Add a backendAddProcessing method

### ISSUE THREAD

**Issue by jotsetung** [lgatto/MSnbase#423]
Some backends will allow immediate data manipulations (e.g. `BackendMemory`) while others don't (`BackendMzR`). I'd propose that we define a `backendApplyProcessingStep` method that takes a `ProcessingStep` object as input (that contains the function to be applied to the spectra, such as `removePeaks`). As a return value the function could return `NULL` (if the data manipulation was applied) or the `ProcessingStep`, in which case it would be added to the queue of the `MSnExperiment`.

**Comment by jotsetung** [comment]
Of course, if we moved the `processingQueue` to the `Backend` we would simply have to call `backendApplyProcessingStep` on the `Backend` - would make sense, because then the `MSnExperiment` is really completely independent of the backend stuff.

**Comment by jotsetung** [comment]
I would leave that to the backend. I would add the above mentioned `backendAddProcessing` that takes the `Backend` as input and a `ProcessingStep`. Whether the backend applies the processing step immediately, or adds it to its `processQueue` is completely up to the developer. For all on-disk backends I would do an on-the-fly processing (with an optional method that forces the application and saves it to the backend (to hdf5 or sql backends).

Usage example:
A `removePeaks,MSnExperiment` would for example create a `ProcessingStep` with `FUN = removePeaks` and all additional arguments as `ARGS` and would call the `backendAddProcessing` on its backend.

**Comment by sgibb** [comment]
My initial idea for creating this whole `Backend` hierarchy was do split the logic/implementation of the data (`Backend` classes), the processing (`ProcessingStep` class and the specific methods) and the user interface (`MSnExperiment`).

Than I had to recognize that we can't completely separate the processing from the backend because of R's functional nature we had to return the spectra and want to avoid thousands of open/close file statements (that's why we removed `backendReadSpectra` and created `backendSpectrapply`).

IMHO we now abolish the separation even more with moving the proccesing queue to the backend (with  `backendAddProcessing` and `Backend@processingQueue`).We could put `@processingQueue` into `MSnExperiment` and provide a `backendSpectrapply(backend, ..., processingQueue, BPPARAM)` method. I know this is just a minor detail but IMHO that's cleaner because the backend should ideally do only memory/file/data-source stuff.

Because `MSnExperiment` knows nothing about its backend we always need to add all processing steps to 
`MSnExperiment@processingQueue` and lazy processing would be the default. While I am not very familiar with the concept from the user point-of-view I can't really think of a disadvantage.

Do we really need to apply the processing immediately for the `BackendMemory`? If that is the case we could provide a slot `@supportsImmediateProcessing` (or something similar).

@jotsetung I don't have a strong argument here. If you can show me a use case for immediate processing in `BackendMemory` or a disadvantage of lazy processing as default we could move on with your `Backend@processingQueue` suggestion.

**Comment by jotsetung** [comment]
I could live with both options, `@processingQueue` in the `MSnExperiment` or in the `Backend`. I also completely understand your concerns - yes, it would be a nicer design to have it in the `MSnExperiment` class.

If we keep the queue I'd suggest to add also a `backendIsReadOnly` method that each backend has to implement and that tells whether changes/data manipulations can be written (in-mem, hdf5) or not (mzR). Reason is explained below.

Having the lazy processing queue is nice, but I want to have also a method that *applies* the data manipulations in the queue. Essentially having a `applyProcessingQueue` function for `MSnExperiment` that the user can use to force applying all the data manipulations. This would be helpful if more computational intense methods are applied to the spectra, something like `smooth` and `pickPeaks` to centroid profile-mode MS data. If this is always done on-the-fly it can slow down the analysis. This is in my eyes also the big advantage of the HDF5 backend, because, while being a on-disk backend, it allows also to write intermediate data to the hdf5 files - otherwise we wouldn't need yet another on-disk backend.

**Comment by jotsetung** [comment]
Thinking it over, we could even remove the `backendSpectrapply` method from the `Backend` to go back to your original design: `Backend` simply takes care of reading/writing stuff.

In `MSnExperiment` we would then need the `spectrapply` to do:
- split the `spectraData` by file and parallelize by file.
- in each thread: 
  - use `backendReadSpectra` to return the `list` of spectra for that file.
  - apply the processing queue (that now is again in `MSnExperiment`) and return its result.

 This then means that data access also for the `BackendMemory` will be parallelized by file. That's the question if you would be OK with this @sgibb . This might not be very clever for simply accessing the data, but might be more efficient if some more computational intense functions are applied to the spectra.

Summarizing, I'm now inclined to go back to the original implememtation/design, but allow `backendReadSpectra` to read data from multiple files (based on `$fileIdx` in the `spectraData` argument). What do you say @sgibb ?

**Comment by jotsetung** [comment]
Dropping this idea altogether. As @sgibb correctly pointed out, the backend should not have to take care of applying data manipulation steps.
