### ISSUE TITLE
Use `file.info` instead of md5 sums to check for changed hdf5 files

### ISSUE THREAD

**Issue by jotsetung** [lgatto/MSnbase#429]
Picking up the discussion in https://github.com/lgatto/MSnbase/pull/426#discussion_r253657248 wit @sgibb's excellent suggestion on the checksum.
We want the file checking to be really fast thus calculating the md5 sum on the file each time is slow. 

Question is when do we need to check for the hdf5 file to be changed.
- each time we read data from the file?
- in the `validObject`?

Following some tests I did over in the `hdf5_jo` branch I think it is crucial to check for changes each time data is read from the file. To check also in `validObject` is optional I think and not really necessary. What we want to check is if some other process changed the file or if the user made a copy of the object and changed data on that.

**Comment by lgatto** [comment]
The reason we need a checksum is that we want to know, from R, if the data has somehow changed on disk. So maybe a checksum in the object on the R side and one in the hdf5 file (to avoid re-computing it) would be ideal. And whenever the data is changed on disk, the checksum is re-computed, and updated in R and the hdf5 file.

**Comment by jotsetung** [comment]
That what you describe is what I have implemented in the *backends_jo* branch 🎉 , the checksum is calculated on the file each time the data is written and the checksum is stored in the file and in the `BackendHdf5` object. For each data reading operation the checksums are then compared.

**Comment by sgibb** [comment]
IMHO we have several problems:
1. The main problem: Copying of writeable file-based backends in R without copying the files, e.g. for HDF5 
```r
ms <- readMSnExperiment(..., backend=BackendHdf5())
mscopy <- ms
## now we have two objects using the same files in the backend
# ... if we modify ms and mscopy in different ways the backend has to throw an error
```

This problem is described in https://github.com/lgatto/MSnbase/issues/405#issuecomment-455159654 and #412.

2. We change the backend files by an external (non-MSnbase) application (e.g. using a c-application to rewrite some peak data in the hdf5 files). ** actually we don't care **

---

We have already discussed multiple solutions:

1. Calculate a checksum over the spectra that are all in memory, write the spectra to the hdf5 file and store the checksum in the backend R object. Each time we read the spectra from hdf5 files we recalculate the checksum and compare it with the stored one.
  - Advantage: detects modifications (even if there were done in an external application)
  - Disadvantage: all spectra from one file have to be in memory for checksum calculation, checksum calculation takes a lot of time, is often useless because nothing changed

2. Calculate a checksum over the spectra that are all in memory, write the spectra and the checksum to the hdf5 file and additionallly store the checksum in the backend R object. Each time we access the spectra from hdf5 files we also read the checksum and compare it with the stored one.
  - Advantage: in comparison to approach one we save time for recalculation of the checksum
  - Disadvantage: all spectra from one file have to be in memory for checksum calculation, checksum calculation takes a lot of time, we can't detect external modification (because the external program won't update the checksum).

3. Calculate a checksum over the written hdf5 file and store it in the R object. Each time we access the spectra we recalculate the checksum and compare it against the stored one.
  - Advantage: faster than approach 1, not all spectra have to be in memory, external modifications could be detected
  - Disadvantage: recalculation of the checksum of the file takes a lot of time

4. Calculate a checksum over the hdf5 file store it in the file and the R object. Each time we access the spectra from hdf5 files we also read the checksum and compare it with the stored one.
  - Advantage: in comparison to approach two we again save time for recalculation of the checksum, not all spectra have to be in memory
  - Disadvantage: the checksum becomes meaningless because it is not a checksum of the spectra anymore but a checksum of the outdated hdf5 file (because it was calculated before the checksum is written to the file). We can't detect external modification and we can't even recalculate/reproduce the checksum (because the file changed after we written the checksum to the file).

5. Use `file.info` to fetch the mtime and atime. Store both in the backend R object. Each time we access the spectra from hdf5 files we compare the mtime and atime of the file with the one we stored in the backend.
  - Advantage: faster than all approaches above, could detect external modification
  - Disadvantage: depends on the support of the file system/platform, independent from the spectra

6. If we don't want to rely on `file.info` I would propose another solution. The `BackendHdf5` class would get a new slot `@modificationCounter` (instead of `@checksums`) that is incremented each time we call `backendWriteSpectra` (we would need a counter for each file). This counter is stored in the hdf5 file as well. Each time we access the spectra we read the counter from the hdf5 file and compare it with the stored one. In fact it is the same approach as 3. but instead of calculating a meaningless checksum we just calculate `modificationCounter + 1`.
  - Advantage: fastest "checksum" approach, would detect `mscopy <- ms; modify(ms); anothermodification(mscopy)`-errors
  - Disadvantage: we can't detect external modifications

I think the most accurate ones are approach 1 and 3 (the latter would be the faster of the two) but both are slow and need a lot of useless checksum recalculation. I am not sure that `file.info` work on all platforms but IMHO that would be the best compromise of a fast and accurate detection of file changes. If we don't want to depend on the file system/platform I would vote for the 6th approach which is more or less the current one but avoids the meaningless checksum calculation and would be faster.

**Comment by jotsetung** [comment]
Nice comprehensive comparison @sgibb !
I vote for approach 6. It is by far the fastest and simplest. And I'd say we don't care (yet) about external modifications - we also don't do that for the `OnDiskMSnExp` where it would be easy to modify the mzML files. Could you add that/modify the approach 4 I have currently implemented in *backends_jo* @sgibb (if @lgatto agrees)?

**Comment by sgibb** [comment]
I can add approach 6 to your branch (or to the *backends* branch after merging). Do you have a better name for the slot? I don't really like `modificationCounter` (I just used it for clarification).
My favorites are: `@modification`, `@step`, `@counter`, `@modificationId`, `@mid`, `@task` (in that order).

**Comment by jotsetung** [comment]
What about `@modCount`? I would keep also the `count` because then it's clear that this contains an (incrementing) number - just having `@modification` doesn't really tell what its content is. But in the end the name doesn't really matter - I could live with any of the options, as long as the slot is documented.

**Comment by sgibb** [comment]
JFTR (if we ever plan to change this): `file.info(...)$mtime` won't work because the resolution of the timestamp depends on the underlying file system and is/could be too low:
> In ext3, the minimum resolution for timestamp was one second. ... in ext4 is 1 nanosecond. 
(from http://www.softpanorama.org/Internals/Unix_filesystems/linux_ext2_ext3.shtml)
