### ISSUE TITLE
Rename MSnExperiment to Spectra?

### ISSUE THREAD

**Issue by jorainer** [lgatto/MSnbase#436]
Following up on yesterdays discussion: `MSnExperiment` and `Spectra` are totally redundant, so why not rename `MSnExperiment` to `Spectra` (or `MSnSpectra`)? 

This would make so much sense, since the object in fact contains spectra - in contrast to the `Chromatograms` which contains chromatograms. From a user perspective that would also be more intuitive because the name of the object tells already what's inside. What do you think @lgatto and @sgibb .

**Comment by lgatto** [comment]
My point was that `Spectra` and `MSnExperiment` (with the in memory list backend) are very close, and hence possibly redundant. So yes, I thought that `Spectra` and `MSnExp` could both be replaced by the new `MSnExperiment`.  

I wasn't suggesting to rename the concept of experiment to `Spectra` - I think this would result in limiting what it actually is. But I do however see value in harmonising the naming of MS experiments and chromatograms. 

Some suggestions:
- `MSnExperiment` and `Chromatograms` (current)
- `Spectra` and `Chromatograms` (consistent and minimal)
- `MSnSpectra` and `Chromatograms` (as suggested above)
- `MSnExperiment` and `Chr[omatogram]Experiment` (consistent and highlighting to concept of experiment) 

And this now lead to another thought. Wouldn't we want to consider different backends for the `Chromatogram` class?

**Comment by jotsetung** [comment]
Regarding backends for `Chromatogram` classes - yes indeed. That's the natural consequence, but for now I would focus on `Spectra`/`MSnExperiment`.

My favorite from your list above is `Spectra` and `Chromatograms` because it simply tells what it is: a list of spectra or a matrix of chromatogram objects.
 
Some thoughts on `Spectra`: in the end it doesn't matter if the data comes from an experiment or is a simple, eventually manually defined, list of spectra. If we can define `Spectra` in a way that it accommodates both it would be great - and we don't need these redundant structures and methods.

In order to allow `MSnExperiment`/`Spectra` to support also manually defined lists of spectra we need:

- a constructor that takes a list of spectra as input - and uses `BackendMemory` by default.
- support that the backend works even if we don't have a `file` associated with it (file can be `NA`).
- the `spectraData` method either returns the content of `@spectraData` or loops through the actual spectra to return their header (which will be the case if we didn't read the data from mzML files).
- we have to be careful with `setBackend` because it will not always be possible to move from an `BackendMemory` to a `BackendMzR`.

With that I think we can replace the current `Spectra` with the `MSnExperiment`.

Let me know if you agree on that and I will give it a shot (would also like your input on that @sgibb ).

**Comment by lgatto** [comment]
> My favorite from your list above is `Spectra` and `Chromatograms` because it simply tells what it is: a list of spectra or a matrix of chromatogram objects.

That's where I somehow disagree. It's not, and shouldn't be a simple list of data. That doesn't cut it when it comes to data analysis. Without metadata, samples/feature annotations, ... data is nothing. Many people have been repeating this message for many years to make sure that researchers report more about their data (when submitting to databases, when reporting in papers, ...). So I think it would be worth considering this point in how to name these objects. 

This actually leads to some other considerations written down in #437.

**Comment by lgatto** [comment]
My suggestion for now would be to make sure `MSnExperiment` is a working replacement for `Spectra`, and then consider the renaming of `MSnExperiment` and/or `Chromatogram`.

**Comment by lgatto** [comment]
I am *not* suggesting here or in #437 to have 
```r
setClass("Experiment",
         contains="VIRTUAL",
         slots = c(
             featureData = "DataFrame",
             sampleData = "DataFrame",
             metadata = "list"
             version = "character"))
```
Or am I? :-/

**Comment by jotsetung** [comment]
You got me wrong. I did not mean `Spectra` has to be a simple list of spectra, I meant the *name* should tell the user what's inside: for `Spectra` it's a list of spectra (with metadata, annotations etc), and `Chromatograms` contains chromatogram objects. `MSnExperiment` does not really tell what it is.

In my opinion the `Spectra` (=`MSnExperiment`) should besides its current use also allow to be used as a list of spectra. That what I will need when analyzing DIA or SWATH data, I need to find and extract MS2 spectra that are associated with chromatographic peaks, and for these I want to add additional metadata to each `Spectrum` class (i.e. what the current `Spectra` object allows).

**Comment by lgatto** [comment]
I exactly got what you meant. But the way you framed it, as a simple list of spectra, is exactly a reflection of the wrong message. It's not about what you meant, but about the perception of what you meant and the name.

**Comment by jotsetung** [comment]
OK, then we continue with `MSnExperiment` and eventually replace `Spectra` later.

**Comment by sgibb** [comment]
I totally agree with @lgatto. I never really understood the need for the new `Spectra` class as "lightweight" replacement for `MSnExp`.

**Comment by jotsetung** [comment]
Implementation of `Spectra` was pure convenience. I needed to have a list of spectra with an easy way to arbitrarily add additional metadata columns. `S4Vectors::SimpleList` provides already all of that with the `mcols` parallel `DataFrame` to the list. I just felt that it was a little bit easier to use than the `MSnExp` with the locked environment.
 
But anyway - I'm more than happy to remove the current `Spectra` and replace that with the `MSnExperiment`. I am currently making sure that `MSnExperiment` objects (mostly with the `BackendMemory`) can be created from spectra without the need of mzML files.

**Comment by lgatto** [comment]
Closing this issue now because (1) the `Spectra` infrastructure has now migrated to its [own package](https://github.com/lgatto/Spectra) and (2) we will (most likely) settle for a high level `MSnExperiment` class with a `Spectra` slot.
