### ISSUE TITLE
consensusSpectrum and combineSpectra: scan information question

### ISSUE THREAD

**Issue by KujawinskiLaboratory** [lgatto/MSnbase#480]
I am using the combineSpectra function with consensusSpectrum based on the code Johannes posted in the FBMN portion of the GNPS website. I like it! Thanks. 
I just a question about the organization of the MS2 information. For each MS1 feature with a consensus MS2 spectrum, one example of the information is as follows:
**FT0035.CP1235.F1.S0660**
I have figured out the following:
**FT0035** is the number of the MS1 feature
**CP1235** ...I don't know what this is
**F1** is the first mzML datafile on the list
**S0660** is the scan number in that first mzML datafile.
I think I have this right so far, though I could not find documentation on this.
My question is this...for a consensus spectrum, I would expect to have information from multiple scans. Is the scan number provided the first scan? I think it is, but I am not 100% certain. If it is the first scan, is there any way to track the full list of scans that were included to make the consensus spectrum?
Thanks again for taking the time to do this in XCMS. Being able to merge MS1 and MS2 features is something I have wanted to do in R for a while.

**Comment by jorainer** [comment]
Hi, sorry for my late reply.

Regarding the naming you are absolutely right. Feature identifiers always start with a **FT**, identifiers starting with **CP** are for **C**hromatographic **P**eaks and the **F** stands for file and **S** for spectrum.

Now, all spectrum variables (such as `msLevel`, ...) for the consensus spectrum are from the **first** spectrum. This is a convention we made, `combineSpectra` will always take all information from the first spectrum - I thought I did document that properly (if not I will add it).

The combined spectrum does not contain any link/list of all spectra from which is was build, but you should have this information anyway. The general workflow to extract the MS2 spectra for each chromatographic peak is the following (works analogously for features, you just call `featureSpectra` instead):

```r
library(xcms)
fl <- system.file("TripleTOF-SWATH/PestMix1_DDA.mzML", package = "msdata")
dda <- readMSData(fl, mode = "onDisk")
## Perform MS1 peak detection
dda <- findChromPeaks(dda, CentWaveParam(peakwidth = c(5, 15)))

## Extract MS2 spectra for each MS1 chromatographic peak
ms2_sps <- chromPeakSpectra(dda)
ms2_sps
Spectra with 258 spectra and 1 metadata column(s):
                   msLevel     rtime peaksCount |     peak_id
                 <integer> <numeric>  <integer> | <character>
  CP001.F1.S0744         2    97.140         25 |       CP001
  CP001.F1.S0746         2    97.550         24 |       CP001
  CP001.F1.S0750         2    97.960         23 |       CP001
  CP002.F1.S1000         2   128.237         16 |       CP002
  CP002.F1.S1008         2   128.737         40 |       CP002
             ...       ...       ...        ... .         ...
  CP111.F1.S5240         2   592.804         24 |       CP111
  CP112.F1.S7344         2   873.714         20 |       CP112
  CP112.F1.S7354         2   874.164         22 |       CP112
  CP112.F1.S7362         2   874.554         22 |       CP112
  CP112.F1.S7430         2   877.903         31 |       CP112
```

Metadata column `"peak_id"` provides the identifier of the chromatographic peak of each MS2 spectrum. You can then combine all MS2 spectra for each chromatographic peak with the `combineSpectra` method, providing `fcol = "peak_id"` to tell the function to combine MS2 spectra with the same value in column `"peak_id"`:

```r
ms2_cons <- combineSpectra(ms2_sps, fcol = "peak_id", method = consensusSpectrum)
ms2_cons
Spectra with 69 spectra and 1 metadata column(s):
                   msLevel     rtime peaksCount |     peak_id
                 <integer> <numeric>  <integer> | <character>
  CP001.F1.S0744         2    97.140         13 |       CP001
  CP002.F1.S1000         2   128.237         16 |       CP002
  CP004.F1.S1808         2   237.050         74 |       CP004
  CP006.F1.S2444         2   326.293          9 |       CP006
  CP007.F1.S2439         2   325.763         14 |       CP007
             ...       ...       ...        ... .         ...
  CP108.F1.S5077         2   570.506         74 |       CP108
  CP109.F1.S5229         2   591.894         19 |       CP109
  CP110.F1.S5234         2   592.304         62 |       CP110
  CP111.F1.S5240         2   592.804         24 |       CP111
  CP112.F1.S7344         2   873.714         15 |       CP112

```

So, with the `combineSpectra` call you loose to information about the original spectra, but you still have this in the `ms2_sps`, in column `"peak_id"`. Note that with `featureSpectra` you would use the column `"feature_id"` instead of `"peak_id"` in the extracted `Spectra` object to combine all MS2 spectra of a **feature** into a single spectrum.

**Comment by jorainer** [comment]
Thanks for the comment @KujawinskiLaboratory ! We are also working on some improved MS data handling (https://RforMassSpectrometry.org) that I plan to integrate sometime to `xcms` - for the better I hope :)

I'm also closing the issue now, feel free to re-open if necessary
