### ISSUE TITLE
MSnbase:: filterRt lead to MSnbase::rtime and xcms::chromPeaks conflict

### ISSUE THREAD

**Issue by jcapelladesto** [lgatto/MSnbase#497]
Dear Msnbase team,

While debugging a function of _osenan/cliqueMS_ (@osenan), I found that the issue was in here (https://github.com/osenan/cliqueMS/blob/9368dc610a85ea2a757cd3620080f1f6dcdcdff2/R/buildNetwork.R#L65). In which  MSnbase::rtime and xcms::chromPeaks are used.

The issue has led us (@mvinaixa) to such line of code where we found that some RT values were missing after performing MSnbase::filterFile after performing _findChromPeaks_ and _filterRt_.
We are unsure wether the cause is a problem with cliqueMS function or caused by a bug in filterRt.
I guess the following code is enough for reproducing:

## Read without filterRt:

```
mzraw <- readMSData(files = mzfile, mode = "onDisk")

cw_onlinexcms_default <- CentWaveParam(ppm = 15, peakwidth = c(5, 20),
                                       snthresh = 6, prefilter = c(3, 100),
                                       mzCenterFun = "wMean", integrate = 1L,
                                       mzdiff = -0.001, fitgauss = FALSE, 
                                       noise = 0, verboseColumns = FALSE, 
                                       roiList = list(), firstBaselineCheck = TRUE, 
                                       roiScales = numeric())

mzData <- findChromPeaks(object = mzraw, param = cw_onlinexcms_default)

```
### This works:
`
cliqueMS:::defineEIC(mzData) # from cliqueMS::getCliques
`

## Apply filterRt:
```
mzData2 <- MSnbase::filterRt(mzData, rt=c(40, 560))
```
### This fails:
`
cliqueMS::::defineEIC(mzData2) # from cliqueMS::getCliques
`
_[1] 1
Error in seq.default(posrtmin, posrtmax, by = 1) : 
  'from' must be of length 1_

### Cause of failure:
```
peaks <- xcms::chromPeaks(mzData)

peaks2 <- xcms::chromPeaks(mzData2)
```
` all(peaks[,"rtmin"]%in%MSnbase::rtime(mzData))`
_[1] TRUE_ 
` all(peaks2[,"rtmin"]%in%MSnbase::rtime(mzData2)) `
_[1] FALSE_ 

Aren't these two lists of RTs (chromPeaks and rtime) expected to **always** match?

**Comment by jorainer** [comment]
I think the problem is that you call directly the `filterRt` method from `MSnbase` on the `xcms` result object (i.e. `XCMSnExp` object). The `XCMSnExp` object extends the `OnDiskMSnExp` object from `MSnbase` (thus inherits all of its methods and you can obviously call all of them on it), but I have implemented a `filterRt` method also in `xcms` to account for the additional information which is present in `XCMSnExp` objects. The `filterRt,OnDiskMSnExp` will only restrict to spectra within the given rt range, while the `filterRt,XCMSnExp` object will do that and in addition also subset the `chromPeaks` matrix. If you use the `filterRt` without the `MSnbase::` all should work fine - if not let me know, because then we might have a problem in `xcms`.

In general I would suggest to avoid calls of type `MSnbase::` or `xcms::` (unless you have a really good reason for it). You should always load all required libraries in R (or import methods from the respective packages, when you use this within the source code of your package).

With the `S4` objects we use in `MSnbase`/`xcms` (and in fact all Bioconductor packages) R *should* always pick up the right method to execute depending on the type of the input object.

**Comment by lgatto** [comment]
I assume this issue can be close. Feel free to re-open if necessary.
