### ISSUE TITLE
Smoothing of chromatogram in retention time domain: `combineSpectraMovingWindow`

### ISSUE THREAD

**Issue by breidan** [lgatto/MSnbase#521]
I am doing profiling of some biological extracts with LC-APCI-MS and my data is rather noisy. Running `xcms::findChromPeaks,CentWaveParam` over the unsmoothed data results in sometimes very irregular peak assignments. So I want to use `combineSpectraMovingWindow` to first smooth the chromatographic data first. I am aware of the issues with MSnExp and OnDiskMSnExp for further processing with `xcms`.

I am using MSnbase 2.12.0 (am currently limited to R3.6) and `combineSpectraMovingWindow` only accepts a `mzd=` argument. That leads to issues with either of the two extremes of the scan range, f.i. at the low end (m/z 100) a mzd=0.01 relates to 100 ppm accuracy while at the high end (m/z 1000) this would be 10 ppm. This is being measured on an Orbitrap and I have better than 5 ppm accuracy which I would like to maintain. 

Now, `meanMzInts` accepts a `ppm=` argument. Anyway that can be issued to  `combineSpectraMovingWindow` and if not, could that be implemented?

**Comment by lgatto** [comment]
I'll leave @jorainer reply to this one.

**Comment by jorainer** [comment]
Now that's a rather advanced question. Thanks for the thorough explanation @breidan . I will have a look at that and come back to you.

**Comment by jorainer** [comment]
I've added parameter `ppm` to `combineSpectraMovingWindows` - you can install the updated version for `MSnbase` 2.12.0 with: `devtools::install_github("lgatto/MSnbase", ref = "RELEASE_3_10")`. The fix is also in PR #522.

Note that you **have** to specify `mzd = 0` if you only want to use the `ppm` - if you don't specify an `mzd` it gets automatically estimated on the data.

Please let me know if this works for you @breidan .

**Comment by breidan** [comment]
@jorainer, thanks for the very fast resolution of this. Seems to be working fine.
